### ISSUE TITLE
Enable CoG to read and merge both ESGF IdP lists

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1004]
WHO: Katarina

Issue: "I was not able to login with my rootAdmin openid because CoG seems to read only /esg/config/esgf_idp_static.xml but not /esg/config/esgf_idp.xml which holds the idp for my "hostnode". After adding my idp to esgf_idp_static.xml login was successful."

Solution: change CoG to read and merge both IdP lists.

**Comment by LucaCinquini** [comment]
This is now done. When CoG is first initialized, the IDP_WHITELIST setting is set by default to:

IDP_WHITELIST = /esg/config/esgf_idp.xml, /esg/config/esgf_idp_static.xml

and CoG will trust the union of tee IdPs contained in the two files.

Note that any CoG upgrade will NOT override the value of the custom setting, so the site administrator might need to manually edit the cog_settings.cfg file to add the first file, if the setting is there already.

**Comment by murphysj** [comment]
Luca to test.

**Comment by LucaCinquini** [comment]
It's actually easy to test as CoG writes out some debugging messages when it first starts up. On my local laptop, I moved the "hydra" IdP to another file, and saw this message when starting:

Loading IdP white list: /esg/config/esgf_idp.xml, last modified: 2015-02-23 10:31:30
Using trusted IdP: https://hydra.fsl.noaa.gov/
Loading IdP white list: /esg/config/esgf_idp_static.xml, last modified: 2015-02-23 09:57:02
Using trusted IdP: https://dev.esg.anl.gov/
Using trusted IdP: https://adm07.cmcc.it/
Using trusted IdP: https://euclipse1.dkrz.de/
Using trusted IdP: https://esgf-data.dkrz.de/
Using trusted IdP: https://esgf-node.ipsl.fr/
Using trusted IdP: https://esgf.nccs.nasa.gov/
Using trusted IdP: https://esg-datanode.jpl.nasa.gov/
Using trusted IdP: https://esg2.nci.org.au/
Using trusted IdP: https://esg.ccs.ornl.gov/
Using trusted IdP: https://pcmdi9.llnl.gov/
Using trusted IdP: https://pcmdi11.llnl.gov/
Using trusted IdP: https://esg01.nersc.gov/
Using trusted IdP: https://dev-hydra.esrl.svc/
Using trusted IdP: https://test-datanode.jpl.nasa.gov/
Using trusted IdP: https://esg-dn1.nsc.liu.se/
