### ISSUE TITLE
Fix "blank-issue" on OpenID login

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1005]
WHO: Katarina

CoG has the same "blank-issue" I mentioned for the new ESG-ORP: Would it be possible to cut blanks before and after the openid while logging in instead of returning an error?

**Comment by LucaCinquini** [comment]
Done, before login form is executed, a little but of client-side javascript removes any leading and trailing white spaces from the openid.

**Comment by murphysj** [comment]
To test: put spaces in front of my openid and login to the production server. see what happens.
Do the same on dev-hydra. If if the issue is no longer there.

**Comment by murphysj** [comment]
verified on dev-hydra, that a) the problem does exist on production...who knew, and fixed on dev-hydra. spaces at the front of the openID were removed.  closing.
