### ISSUE TITLE
Change the default email address for rootAdmin

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1006]
WHO: Katarina

The default email address for rootAdmin is adminuser@test.com. Can't we just use the mail.admin.address in esgf.properties as default? I'm not sure all admins will change the default ... Or is this planned for later use in production?

**Comment by LucaCinquini** [comment]
This is now done: the ESGF property 'mail.admin.address', if found, is used for two purposes:
o to set the value of the CoG property EMAIL_SENDER (the email that sends CoG notifications to the users) - only if this property is not set already
o the initial value of the CoG site administrator - only when the site administrator is first created

Note that I think the ESGF property 'mail.admin.address' does not typically correspond to a real person email receiving address, so the site administrator will still have to change this address to their real email.

**Comment by murphysj** [comment]
Is there a way to test this pre-release, or should Katarina test post-release?

**Comment by LucaCinquini** [comment]
The only way to test is to wipe out the database and re-install CoG from scratch. I don't recommend you do it, but I just had to go through that process on my laptop and it seems to be working. I can close this ticket if you wish.

**Comment by murphysj** [comment]
works for me.

On Tue, Mar 10, 2015 at 12:39 PM, Luca Cinquini <notifications@github.com>
wrote:

> The only way to test is to wipe out the database and re-install CoG from
> scratch. I don't recommend you do it, but I just had to go through that
> process on my laptop and it seems to be working. I can close this ticket if
> you wish.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1006#issuecomment-78118991>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
Luca says he has tested this. closing.
