### ISSUE TITLE
Change project tag behavior in Project Browser

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1008]
Who: Cecelia

Cecelia suggested the following improvements to the project browser:

o Selecting a tag should always switch to the 'All' tab
o Insert a tag Reset button

**Comment by LucaCinquini** [comment]
Done. The buttons might need some CSS styling applied. Also some cross-browsing testing would be good.

The tags now have their case preserved. The case of existing tags can be changed by using the Django Admin interface.

**Comment by murphysj** [comment]
Luca,
We all ready had a bunch of tickets in the system for this. I will close
those as duplicates.

On Fri, Feb 27, 2015 at 7:18 AM, Luca Cinquini <notifications@github.com>
wrote:

> Assigned #1008 <https://github.com/EarthSystemCoG/COG/issues/1008> to
> @murphysj <https://github.com/murphysj>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1008#event-243287545>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
Sorry, I looked at the current release and just saw one that was not exactly what I needed.
thanks, L

On Feb 27, 2015, at 7:19 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:

Luca,
We all ready had a bunch of tickets in the system for this. I will close
those as duplicates.

On Fri, Feb 27, 2015 at 7:18 AM, Luca Cinquini <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Assigned #1008 <https://github.com/EarthSystemCoG/COG/issues/1008> to
> @murphysj <https://github.com/murphysj>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1008#event-243287545>.
>



--
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
Phone: 303-497-7753

**Comment by murphysj** [comment]
She also wanted to save tags. Did you look at the mockup? we not even decided on a design yet.

**Comment by murphysj** [comment]
Reset works

**Comment by murphysj** [comment]
The changing to the All tab from the This tab works, but it draws everything first and THEN redraws it with just the correct list of projects.

**Comment by LucaCinquini** [comment]
Ok can you try to play with the order of the JS functions to see if you can improve the rendering.
thanks, L

**Comment by murphysj** [comment]
will do

On Tue, Mar 10, 2015 at 12:41 PM, Luca Cinquini <notifications@github.com>
wrote:

> Ok can you try to play with the order of the JS functions to see if you
> can improve the rendering.
> thanks, L
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1008#issuecomment-78119415>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
This took quite a while to diagnose since I had to learn how the Javascript functions were working and interacting with YUI. 

What I ended up doing is moving the goToTab function out of the onClick for the Go button and into the input for tag text input box. 

This means that now, when a user clicks on that text box to enter a tag, they are taken to the All tab first.

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
