### ISSUE TITLE
Deleting a note created by a deleted user throws an error

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1012]
WHO: Sylvia

on the production server
https://www.earthsystemcog.org/post/detail/2246/

This was created by me, under my old account. I suspect that when you disconnected users from objects, you forgot notes. just a guess though.

**Comment by murphysj** [comment]
Hi Sylvia,
        I think we decided some time ago that if we delete a user, we don’t want to delete the documents they have uploaded, including notes, The current specification for the “Doc” model includes:

 author = models.ForeignKey(User, related_name='documents', verbose_name='Publisher', blank=False, null=True, on_delete=models.SET_NULL)

Right now, the server error is caused by logging an event when the notes are deleted for a user that has already being deleted. If you file a bug report for this issue, I’ll fix it in this release.

thanks, Luca

**Comment by LucaCinquini** [comment]
Done

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
