### ISSUE TITLE
People listing throws YSD if user in list no longer exists

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1018]
WHO: Sylvia

Found in 2.11 testing on dev-hydra. Do a people listing on cog. my old account used to be there. it says it can't find it and throws a YSD. 

Do a people listing on cmip6. I am not a user there. It lists ok.

**Comment by LucaCinquini** [comment]
This problem is solved in the sense that the people listing shows up. But - when you click on the user profile for that account, and yo hare redirected to NOAA, another strange problem happens because that account does not exist any more. Somehow we need to upgrade a project list of people to check for accounts that have been deleted - but that is another ticket for another release.

**Comment by murphysj** [comment]
Opened a ticket for the follow-on work. This will be a known bug for 2.11.

On Tue, Mar 10, 2015 at 1:19 PM, Luca Cinquini <notifications@github.com>
wrote:

> This problem is solved in the sense that the people listing shows up. But
> - when you click on the user profile for that account, and yo hare
> redirected to NOAA, another strange problem happens because that account
> does not exist any more. Somehow we need to upgrade a project list of
> people to check for accounts that have been deleted - but that is another
> ticket for another release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1018#issuecomment-78127279>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
verified on dev-hydra that the link on the people page no longer throws a YSD, have verified that the people listing fails. That is a separate ticket. closing.
