### ISSUE TITLE
Incorrect removal of remote memberships

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1027]
Who: Cecelia

Hi, lately every time I go to a CU CoG page for the first time I see
Server Error (500). When I click again, the error goes away.
Still, not everyone may know to click again.  Any ideas on what's
causing this? Thanks - c

**Comment by LucaCinquini** [comment]
After much debugging, I think there was a condition that might have caused an error. If a user is completely removed from a remote group, that membership is never taken away from the local database. As a consequence, if the membership is granted again on the remote CoG, that information cannot be saved to the local database because it already exists, causing a database error for unique key constraint.

**Comment by LucaCinquini** [comment]
The issue should now be fixed, remote memberships are removed and re-assigned on the local host.

**Comment by murphysj** [comment]
Can you explain how this affected Cecelia?

She had membership in coupledNEMS. That did not change, and that project stayed at NOAA. What do you mean by remote group? Do you mean user account? If so that did not change either. All our accounts are at NOAA.

**Comment by LucaCinquini** [comment]
Well I was thinking that IF her membership was cancelled and then re-instated, that might have caused the problem ? I don’t know if that is what actually happened.
L

On Mar 19, 2015, at 9:10 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you explain how this affected Cecelia?

She had membership in coupledNEMS. That did not change, and that project stayed at NOAA. What do you mean by remote group? Do you mean user account? If so that did not change either. All our accounts are at NOAA.

**Comment by murphysj** [comment]
Hard to say. Fixed for now.

I did go in and assigned my account membership in a project on the NOAA
node. That did not effect things.




On Thu, Mar 19, 2015 at 9:37 AM, Luca Cinquini <notifications@github.com>
wrote:

> Well I was thinking that IF her membership was cancelled and then
> re-instated, that might have caused the problem ? I don’t know if that is
> what actually happened.
> L
>
> On Mar 19, 2015, at 9:10 AM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> Can you explain how this affected Cecelia?
>
> She had membership in coupledNEMS. That did not change, and that project
> stayed at NOAA. What do you mean by remote group? Do you mean user account?
> If so that did not change either. All our accounts are at NOAA.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1027#issuecomment-83618606>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1027#issuecomment-83637405>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753
