### ISSUE TITLE
Creating account dumps user at the NOAA ESGF-ESRL project

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1032]
WHO: Cecelia

Start with this URL:
http://cog-esgf.esrl.noaa.gov/projects/wam_gip/

Click "Create Account"
Fill out the page

Result: Taken to the login page

Login

Result: Taken you to the ESGF-ESRL front page.

What we want is to be taken back to the URL we started from

**Comment by murphysj** [comment]
Started at project on CU node:
https://www.earthsystemcog.org/projects/climatewater/

process was the same, we end up at the ESRL-CoG project at NOAA

**Comment by LucaCinquini** [comment]
Can you add this to another release ? We never said that creating an account should take you back to where you started - intact, I don't think web sites normally work that way. After creating an account, you are typically redirected to some standard page, like the site home page.

**Comment by murphysj** [comment]
Was just going to email you about this.

Cecelia is happy to make this part of a patch after 2.11

This is the problem. People are getting dumped to a project they know
nothing about. She sends them a link to project X and after creating an
account they are dumped at project Y.  It is causing all sorts of confusion.

She would like them taken back to the URL they started from.

On Mon, Apr 6, 2015 at 2:41 PM, Luca Cinquini <notifications@github.com>
wrote:

> Can you add this to another release ? We never said that creating an
> account should take you back to where you started - intact, I don't think
> web sites normally work that way. After creating an account, you are
> typically redirected to some standard page, like the site home page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1032#issuecomment-90233177>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
This is now implemented. The "Create Account" link comes with a "next" parameter that will always redirect to the original page where it was clicked, even if that page is on a different web site.

Implementation was very laborious. To test, you can run your local CoG instance with a setting of:
IDP_REDIRECT=https://dev-hydra-httpd.esrl.svc
to redirect account creation to dev-hydra

**Comment by murphysj** [comment]
My first two tests failed.

I went to my local sandbox and a private project.

I clicked create account. 

I filled in the info.

Clicking submit is taking me BACK  the account page to fill in institution, etc

when done, it leaves me there.

**Comment by murphysj** [comment]
When it takes me back to the account page it is the account page on localhost.

**Comment by murphysj** [comment]
ok, turns out that the accounts must be able to federate and the css branch was not federated with dev-hydra. We turned that on and the testing was possible.

**Comment by murphysj** [comment]
Tested starting from a private project and a public project on my local system. In both cases I was dumped back to my project after creating an account on dev-hydra. 

closing.
