### ISSUE TITLE
Deal with ESG OpenIDs

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1035]
Hi Luca,

I know some of the older ESG open ids are not still usable.
Could we put a statement on the login page that says something
like if your openid includes or looks like <this> then you cannot
use it and should create a new one?

Thanks,
Cecelia

**Comment by murphysj** [comment]
Hi Cecelia,
        can we file this ticket for the next release ? I’d like to explore wether this is a limitation we can overcome with simple configuration, or
an intrinsic problem with exchanging openid attributes that cannot be solved.
thanks, L

**Comment by murphysj** [comment]
Once we switch to the new pulldown mechansim, this may be taken care of if any of the older IDPs are not in the list. 

We can just put text above indicating that only those IDPs in the list are useable.

**Comment by LucaCinquini** [comment]
-IF- we switch to the pull-down - not really working for lots of the sites right now…
L

On Apr 7, 2015, at 8:40 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Once we switch to the new pulldown mechansim, this may be taken care of if any of the older IDPs are not in the list.

We can just put text above indicating that only those IDPs in the list are useable.

**Comment by murphysj** [comment]
Joy. I will move THAT ticket out of 2.11 then.

On Tue, Apr 7, 2015 at 8:42 AM, Luca Cinquini <notifications@github.com>
wrote:

> -IF- we switch to the pull-down - not really working for lots of the sites
> right now…
> L
>
> On Apr 7, 2015, at 8:40 AM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> Once we switch to the new pulldown mechansim, this may be taken care of if
> any of the older IDPs are not in the list.
>
> We can just put text above indicating that only those IDPs in the list are
> useable.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1035#issuecomment-90588018>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1035#issuecomment-90588463>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
Hi Luca, this was really just for adding text, not solving the problem.
Is there something that identifies the older openids?
Thanks,
Cecelia

**Comment by murphysj** [comment]
I think the old open ids all contain the “/myopenid/“ string…

The only ones that are really used contain "www.earthsystemgrid.org/myopenid/“ because NCAR is the only place that use the old gateway software,
but I don’t think it looks good to say that ESGF does not support open ids from “www.earthsystemgrid.org”. But we can say that we don’t support “/myopenid/“,
that would be ok.

If you want to suggest some text, I can include it in the login page.

thanks, L

**Comment by murphysj** [comment]
Okay Luca, thanks.

Maybe something like this:

If you already have an ESGF OpenID, you can use it to log onto ESGF-CoG below.
However, if your openid contains /myopenid/ it is likely an older version that is no
longer supported.

Thanks,

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
