### ISSUE TITLE
No way to bounce back and forth between Data Cart and previous search

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1042]
WHO: Bjorn Stevens

it was not clear how to get from my shopping cart back to the advanced search page.  

When I did this by hitting the back button all of my search parameters were lost.

**Comment by murphysj** [comment]
Consider just opening the data cart in its own tab.

**Comment by murphysj** [comment]
We asked Bjorn if this was acceptable. We'll see what he says.

**Comment by LucaCinquini** [comment]
I inserted a link "Back to Search" in the Data Cart that will take the user to their last search, including restoring the search constraints and the search results.

Again I think we should consider having this link on every page, replacing the current "My Profile" link.

**Comment by murphysj** [comment]
Bring that up on Tuesday. I also think the My Profile link should be at the
top.

It makes sense for the data links to be together

If there is no value for that link, does it appear?

On Thu, May 14, 2015 at 11:16 AM, Luca Cinquini <notifications@github.com>
wrote:

> I inserted a link "Back to Search" in the Data Cart that will take the
> user to their last search, including restoring the search constraints and
> the search results.
>
> Again I think we should consider having this link on every page, replacing
> the current "My Profile" link.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1042#issuecomment-102106327>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
completed as part of #1059. We can add the links elsewhere too if we want.
