### ISSUE TITLE
Race condition when saving user  tags

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1054]
Who: Ceelia

500 error again when I hit CoG pages for the first time
Getting that error again.

**Comment by LucaCinquini** [comment]
Hi Luca, yes, I'm using my own account. 

This is what you said last time:
After much debugging, I think there was a condition that might have caused an error. If a user is completely removed from a remote group, that membership is never taken away from the local database. As a consequence, if the membership is granted again on the remote CoG, that information cannot be saved to the local database because it already exists, causing a database error for unique key constraint.

I don't think I've changed anything about my account or access, so I'm not
sure why it would have reappeared.
It can wait until next week, it's not urgent.

- c

**Comment by LucaCinquini** [comment]
I think I have traced this error to a possible race condition when saving information to the database: if multiple views are invoked at once, for example through multiple browser tabs, and if the internet connection is slow, a view might try to update the database at the same time as the other.
In particular, this error is caused by an exception when updating the user project tags.

**Comment by LucaCinquini** [comment]
I think I have protected the view against this condition by locking the user profile object in the database.
If this work, we might need to apply the same technique to other parts of CoG where a race condition might exist.

**Comment by murphysj** [comment]
@LucaCinquini 
I assume since release 1.11.2 is live that you consider this ticket closed?
