### ISSUE TITLE
Expose back links in Data Cart

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1059]
Who: Robert Ferraro

Once I empty my data cart, there are no navigation links left to take me back to my project pages …

**Comment by murphysj** [comment]
This is similar to #1042 , which is Bjorn's request to be able to go back from the Data Cart to the Advanced Search Page. 

In this case did Robert want to go back to the ASP or to the project home page?

**Comment by LucaCinquini** [comment]
More from Robert on this issue:

I would like to see the “go back to your last search” on the Data Cart page as well.  Right now, that page is completely unaffiliated with the CoG project that you come from.  Yes - the back button on the browser does work to get back, but I think you need to provide a “back to search” link as well.   I would put it on the left just under the dark green bar.  (The old search interface had tabs at the top to select data cart or search …)

I get that the data cart is potentially shared across multiple CoG projects on the particular CoG instance (in this case, the ESGF@NASA/JPL node).  I can imagine a user wanting to fill his cart from several project searches, so you should think about how to do that.  One idea is to keep a list of all CoG projects the user belongs to on the search page so that one can go back to a different project search before doing a download.  It could perhaps be a dropdown menu, with the last search instance being the one visible.  That way, the Go Back can be changed if the user desires, or the default is the last search.

**Comment by murphysj** [comment]
@LucaCinquini 
I tweaked this page slightly because the "Back to Last Search" text was buried in all the other text on the page. 

I added a header and moved the name of the node to the header
I simplified the link text and make the entire text clickable
I added a couple of lines of empty space between that text and the start of the datacart results.

See if that is ok.

**Comment by murphysj** [comment]
@LucaCinquini 

When I click on the actual "Return to Last Search" text in the Datacart, it does take me back to the search page, but that is all. Shouldn't the actual search results be there as well?

**Comment by LucaCinquini** [comment]
It should remember both the constraints and the results, if that was the last thing you did. It seems to be working for me, maybe you can show me next Tuesday.
thanks, L

On May 15, 2015, at 11:27 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucaCinquini<https://github.com/LucaCinquini>

When I click on the actual "Return to Last Search" text in the Datacart, it does take me back to the search page, but that is all. Shouldn't the actual search results be there as well?

**Comment by murphysj** [comment]
@LucaCinquini 
It is working as expected on dev-hydra. closing.
