### ISSUE TITLE
Make all ESGF Openids work with CoG

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1063]
Who: Luca

It has been noted that on the CoG NOAA installation some ESGF open ids do not work, for examples those issued by PCMDI, IPSL or DKRZ.

**Comment by LucaCinquini** [comment]
It seems like this issue can be solved by applying all of the following changes:

o Python installation must be upgraded to 2.7.9 to take advantage of changes in SSL support

o Additionally, when using CoG behind the Apache httpd server, mod_wsgi.so must be recompiled with the new Python, and httpd started with the option LD_lIBRARY_PATH pointing to the new python shared library (otherwise mod_wsgi will pickup the older Python shared library)

o Additionally, the environment variable SSL_CERT_DIR must be defined to point to /etc/grid-security/certificates, so that url lib knows which certificates to trust

o pycurl must NOT be in the python site-packages, otherwise the package python-openid will use it instead of url lib, and the SSL_CERT_DIR will have no effect

**Comment by LucaCinquini** [comment]
With the above changes, it was verified that dev-hydra can correctly use open ids from the following ESGF nodes:

https://pcmdi9.llnl.gov/esgf-idp/openid/......
https://esgf-node.ipsl.fr/esgf-idp/openid/.........
https://esg-datanode.jpl.nasa.gov/esgf-idp/openid/....
https://hydra.fsl.noaa.gov/esgf-idp/openid/.....
https://ceda.ac.uk/openid/.....
https://esgf-data.dkrz.de/esgf-idp/openid/...

**Comment by LucaCinquini** [comment]
All the above URLs also work on hydra. The additional thing to fix was that the Python virtual environment created by CoG MUST be created by pointing to the 2.7.9 installation, like so:

virtualenv -p /usr/local/python-2.7.9/bin/python venv

Otherwise, virtualenv will use the Python installation with which it was created, which is 2.7.2.

**Comment by LucaCinquini** [comment]
This ticket can be checked by obtaining a few new open ids from the ESGF nodes mentioned above, and using them to log onto hydra.

**Comment by murphysj** [comment]
@LucaCinquini 
FYI, the URLs above don't link to actual nodes. They are XML files. 

I got a DKRZ openID: https://euclipse1.dkrz.de/esgf-idp/openid/murphysj  and used it to login

**Comment by murphysj** [comment]
I got an IPSL openID:
https://esgf-node.ipsl.fr/esgf-idp/openid/murphysj
and used it to login

**Comment by murphysj** [comment]
seems to be working. closing.
