### ISSUE TITLE
Hide private projects in project browser, unless the user is a member

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1064]
Who: Cecelia, Rocky

We should go back to the situation where private projects do not show up in the project browser, unless a user is a member of the project. But -for project members- private project should be federated across all sites, so be visible to that user no matter what CoG instance they are visiting.

**Comment by LucaCinquini** [comment]
Done. Note that a CoG administrator at site A will be able to see ALL projects (including private projects) that are hosted on that site, but will NOT be able to see private projects at another site B, unless he/she is a ember of that project.

To make this happen, I changed how the methods "userHasUserPermission()" and "userHasAdminPermission()" work: now the authorization logic in this methods is based on groups, not on django permissions (since a django staff user automatically has ALL django permissions).

**Comment by murphysj** [comment]
@LucaCinquini 

I created a new account on CU (redirecting to NOAA) and added that account to one of the private projects at NOAA.

I then logged into dev-hydra using that account. I don't see the private project listed under All nor under My.

Is there a lag? Dev-hydra is synced with NOAA.

**Comment by LucaCinquini** [comment]
On May 13, 2015, at 2:59 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucaCinquini<https://github.com/LucaCinquini>

I created a new account on CU (redirecting to NOAA) and added that account to one of the private projects at NOAA.

I then logged into dev-hydra using that account. I don't see the private project listed under All nor under My.

Is there a lag? Dev-hydra is synced with NOAA.

Syncing happens only once a day. You can manually trigger the sun by logging into dev-hydra as administrators and using the “Configure Peers” options. Syncing should import the hidden project from NOAA to dev-hydra and it should show up in your new users’s list. I think.

**Comment by murphysj** [comment]
Syncing worked
Verified on dev-hydra. Closing.
