### ISSUE TITLE
Help page for using Globus Online

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1074]
Who: Robert

Robert asked that all explanation about using Globus Online be included in a separate page, probably hosted on CoG CU so it can be maintained just like the Search page. Attached is a screen that can be used as starting point.

**Comment by LucaCinquini** [comment]
![go](https://cloud.githubusercontent.com/assets/637059/7614079/be650460-f951-11e4-9501-8ac852062cc9.png)

**Comment by LucaCinquini** [comment]
Instructions have been created for both the users and the administrators:

https://www.earthsystemcog.org/projects/cog/globus_esgf_cog
https://www.earthsystemcog.org/projects/cog/admin_globus_esgf_cog

**Comment by murphysj** [comment]
@LucaCinquini 

I have looked at the documentation. 

Send me two screenshots. A small one showing the "Globus Download" link, and another showing the page where you can choose your options (script or web). 

I will add those to the page.

I also linked the documentation into the list of tutorials about data services.

**Comment by murphysj** [comment]
@LucaCinquini 
modified help page with images and pretty cosmetics. 
https://www.earthsystemcog.org/projects/cog/globus_esgf_cog
