### ISSUE TITLE
User thumbnails are not federated

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1076]
WHO: Sylvia

Don't know if this is a federation issue or some sort of path issue.

1) Go to the CoG Governance Roles page. 
2) No thumbnail shows up for Sylvia
3) Click through the account until you get to NOAA/hydra, where the account lives
4) There is a picture associated with that account.

**Comment by murphysj** [comment]
We can't work on this right now because we have turned off federation due to the ESGF issues. Moving out of this milestone.

**Comment by murphysj** [comment]
Way to fix this is to use the URL to the image.

**Comment by LucaCinquini** [comment]
Now the thumbnail of a user is retrieved by URL from either the local or a remote site.
Note that this work only for "real" users, not for stub "Collaborator" objects that are entered manually by name in listing of people belonging to a project. These later objects are NOT federated across sites and their picture is never shared.

**Comment by LucaCinquini** [comment]
Note also that it will be impossible to truly test this ticket until after the new version is released at multiple sites across which people can login with openid SSO.

**Comment by LucaCinquini** [comment]
Sylvia, you still can test that this change does not break the display of images and thumbnails for local users.

**Comment by murphysj** [comment]
tested and we have thumbnails working locally. will keep this open until my post release test.
