### ISSUE TITLE
Django admin interface can override user information

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1079]
WHO: Sylvia

If a user account is on one node, but they are project members on a different node, their info is transferred...sort of.  The names can be changed using the Django interface. This overrides what is in their profile. There should be one definitive source.

**Comment by murphysj** [comment]
This is related to the lack of syncing on user accounts.

**Comment by murphysj** [comment]
We can't work on this right now because federation is turned off due to the ESGF issues. Moving out of this milestone.

**Comment by LucaCinquini** [comment]
Well, I think this ticket does not make a lot of sense: node administrators should NOT ever ever ever use the django admin interface unless they know really well what they are doing, in which case they assume all responsibilities. In particular, why would they mess up with user personal information, on the original node, or any other ?
So I am in favor of closing this ticket - unless we are planning on hiding the django admin interface ?

**Comment by murphysj** [comment]
I think this ticket is an artifact of troubleshooting the non-federation of
user accounts, which you have now fixed. If someone changes something on
their profile on the remote machine, that information should now propagate
to the user stub on the local node yes?

On Wed, Nov 4, 2015 at 1:21 PM, Luca Cinquini <notifications@github.com>
wrote:

> Assigned #1079 <https://github.com/EarthSystemCoG/COG/issues/1079> to
> @murphysj <https://github.com/murphysj>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1079#event-454939970>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753
