### ISSUE TITLE
Accounts deleted at NOAA still showing up at CU

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1084]
WHO: Sylvia

There are some deleted accounts still showing up in the list of all users at CU. Somehow the syncing is not working as expected.

**Comment by LucaCinquini** [comment]
Actually, if you think this is the problem - accounts are not periodically synced between sites. When a user from site A logs onto site B a new account is created at site B, but accounts are never cross-checked between sites on a periodic basis. That would be a big performance and scalability issue. Not sure it can be addressed.

On Jun 11, 2015, at 1:04 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


WHO: Sylvia

There are some deleted accounts still showing up in the list of all users at CU. Somehow the syncing is not working as expected.

**Comment by murphysj** [comment]
THat makes sense if a user has an account at DKRZ and then logs into NOAA,
but what about CU, which has no account IDP of its own.

If a user tries to create an account at CU, they are directed to NOAA. The
account is created hosted there. If the account on NOAA gets deleted, CU
still sees it. It is not like there is a new account at CU. There is just
one, it just happens to live at NOAA.

Shouldn't things be shared better in this case?

On Thu, Jun 11, 2015 at 1:10 PM, Luca Cinquini <notifications@github.com>
wrote:

> Actually, if you think this is the problem - accounts are not periodically
> synced between sites. When a user from site A logs onto site B a new
> account is created at site B, but accounts are never cross-checked between
> sites on a periodic basis. That would be a big performance and scalability
> issue. Not sure it can be addressed.
>
> On Jun 11, 2015, at 1:04 PM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> WHO: Sylvia
>
> There are some deleted accounts still showing up in the list of all users
> at CU. Somehow the syncing is not working as expected.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1084>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1084#issuecomment-111244961>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
Ok I see your point, unfortunately. We could make CU checks for validity of accounts at NOAA periodically.

On Jun 11, 2015, at 1:20 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:

THat makes sense if a user has an account at DKRZ and then logs into NOAA,
but what about CU, which has no account IDP of its own.

If a user tries to create an account at CU, they are directed to NOAA. The
account is created hosted there. If the account on NOAA gets deleted, CU
still sees it. It is not like there is a new account at CU. There is just
one, it just happens to live at NOAA.

Shouldn't things be shared better in this case?

On Thu, Jun 11, 2015 at 1:10 PM, Luca Cinquini <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Actually, if you think this is the problem - accounts are not periodically
> synced between sites. When a user from site A logs onto site B a new
> account is created at site B, but accounts are never cross-checked between
> sites on a periodic basis. That would be a big performance and scalability
> issue. Not sure it can be addressed.
>
> On Jun 11, 2015, at 1:04 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>
> <mailto:notifications@github.com>> wrote:
>
>
> WHO: Sylvia
>
> There are some deleted accounts still showing up in the list of all users
> at CU. Somehow the syncing is not working as expected.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1084>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1084#issuecomment-111244961>
> .
>



--
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
Phone: 303-497-7753

**Comment by murphysj** [comment]
will probably need to make it more general. If a node is installed w/o
ESGF, they are going to get their accounts from someplace else. Where would
that be? Will it always be NOAA or can that node choose an IDP node?

On Thu, Jun 11, 2015 at 3:05 PM, Luca Cinquini <notifications@github.com>
wrote:

> Ok I see your point, unfortunately. We could make CU checks for validity
> of accounts at NOAA periodically.
>
> On Jun 11, 2015, at 1:20 PM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
> THat makes sense if a user has an account at DKRZ and then logs into NOAA,
> but what about CU, which has no account IDP of its own.
>
> If a user tries to create an account at CU, they are directed to NOAA. The
> account is created hosted there. If the account on NOAA gets deleted, CU
> still sees it. It is not like there is a new account at CU. There is just
> one, it just happens to live at NOAA.
>
> Shouldn't things be shared better in this case?
>
> On Thu, Jun 11, 2015 at 1:10 PM, Luca Cinquini <notifications@github.com
> <mailto:notifications@github.com>>
> wrote:
>
> > Actually, if you think this is the problem - accounts are not
> periodically
> > synced between sites. When a user from site A logs onto site B a new
> > account is created at site B, but accounts are never cross-checked
> between
> > sites on a periodic basis. That would be a big performance and
> scalability
> > issue. Not sure it can be addressed.
> >
> > On Jun 11, 2015, at 1:04 PM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>
> > <mailto:notifications@github.com>> wrote:
> >
> >
> > WHO: Sylvia
> >
> > There are some deleted accounts still showing up in the list of all users
> > at CU. Somehow the syncing is not working as expected.
> >
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/EarthSystemCoG/COG/issues/1084>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EarthSystemCoG/COG/issues/1084#issuecomment-111244961>
> > .
> >
>
>
>
> --
> ******************************************
> Sylvia Murphy
> NESII/CIRES/NOAA Earth System Research Laboratory
> 325 Broadway, Boulder CO 80305
> Time Zone: U.S. Mountain
> Web: http://www.esrl.noaa.gov/nesii/
> Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
> Phone: 303-497-7753
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1084#issuecomment-111250604>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1084#issuecomment-111277409>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
We can't work on this right now because federation is turned off due to the ESGF issues. Moving out of this milestone.

**Comment by LucaCinquini** [comment]
I have implemented a new django command that will loop over all the users in the database: if the user has a remote home node, it will try to access the user profile, and if it is not available, it will the local user stub.

The command can be run as:
python manage.py sync_users

either from the command line, or through a cron job.

**Comment by murphysj** [comment]
How does this fix the issue? I would think that if the account is deleted
at NOAA, the stub at CU should also be deleted when you run the sync_users
command....

On Wed, Nov 4, 2015 at 11:43 AM, Luca Cinquini <notifications@github.com>
wrote:

> Assigned #1084 <https://github.com/EarthSystemCoG/COG/issues/1084> to
> @murphysj <https://github.com/murphysj>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1084#event-454833921>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
Yes, I forgot the word "delete" in the previous comment, see correction...

**Comment by murphysj** [comment]
Ok, since this is a program that is run, the node administrator can decide how frequently to do it. At CU for instance, we might want to do it as part of the release process?

**Comment by LucaCinquini** [comment]
Yes, or as part of a cron job…
L

On Nov 4, 2015, at 2:41 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, since this is a program that is run, the node administrator can decide how frequently to do it. At CU for instance, we might want to do it as part of the release process?

**Comment by murphysj** [comment]
@LucaCinquini 
I am assuming that is one we can't test until after the fact?

**Comment by LucaCinquini** [comment]
Probably - although I did test it using my local CoG and the JPL CoG…
L

On Nov 5, 2015, at 8:39 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucaCinquini<https://github.com/LucaCinquini>
I am assuming that is one we can't test until after the fact?

**Comment by murphysj** [comment]
Ok, will close this then.
