### ISSUE TITLE
Migrate all current project users to be contributors

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1092]
Who: Luca

As we introduce the 'contributor' role, we must make sure that current users can edit the project pages, therefore make all of the 'contributors'.

**Comment by LucaCinquini** [comment]
The migration script has been created and will need to be run after the release has been installed.
Note that the script also remove the permission objects "project_name Admin Permission" and 'project_name User Permission' which I don't think are used at all (cog authorization being based on groups, not permissions).

**Comment by murphysj** [comment]
spot checked on dev-hydra. Closing.
