### ISSUE TITLE
Create 'contributor' permission and group for all existing projects

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1093]
Who: Luca

We must make sure that all existing projects have an associated 'contributor permission and group, otherwise the site will generate errors. Must execute update script at all sites after upgrading to this release.

**Comment by murphysj** [comment]
change the permissions in the html template hasUserPermission to hasContributorPersmission

and ditto for the views

**Comment by murphysj** [comment]
These permissions will be converted to Contributor

forms_other.py
   * news_form: must be a contributor to post news, so don't let them see the projects in the form
news_detail.html 
news_list.html
  * update or delete news

_comments.html
  * comments restricted to authenticated users who are Contributors
doc_detail.html
  * updated documents limited to Contributors
doc_list.html
  * Contributors can delete documents in file listing


'''These permissions will remain with Users'''
forum/_comments.html
   * comment on a forum post
forum_detail.html
   * start a new thread
thread_detail.html
  * post to a thread
topic_detail.html
  * start a new topic

**Comment by murphysj** [comment]
committed, now need to test

**Comment by murphysj** [comment]
Testing test_user:

Can I:

* View news...YES
* List news ...YES
* Post news...NO
* Delete news...NO
* Update news...NO

* View Post...YES
* View Private Post...YES
* Create Post...NO
* Update Post...NO
* Delete Post...NO

**Comment by LucaCinquini** [comment]
Hi Sylvia,
as I mentioned before, you also need to make sure that the “view” has the proper security check as well. I.e. if I am just a “user”, but someone told me the URL to create a POST, can I manually invoke it ? We need to make sure the answer is NO. Perhaps you are already doing this.
thanks, L

On Jul 20, 2015, at 12:21 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Testing test_user:

Can I:

  *   View news...YES
  *   List news ...YES
  *   Post news...NO
  *   Delete news...NO
  *   Update news...NO

  *   View Post...YES

  *   View Private Post...YES
  *   Create Post...NO
  *   Update Post...NO
  *   Delete Post...NO

**Comment by murphysj** [comment]
I go into the views and changed the permissions there, but have not been
testing going to the url directly, I will add that to the list

On Mon, Jul 20, 2015 at 12:26 PM, Luca Cinquini <notifications@github.com>
wrote:

> Hi Sylvia,
> as I mentioned before, you also need to make sure that the “view” has the
> proper security check as well. I.e. if I am just a “user”, but someone told
> me the URL to create a POST, can I manually invoke it ? We need to make
> sure the answer is NO. Perhaps you are already doing this.
> thanks, L
>
> On Jul 20, 2015, at 12:21 PM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> Testing test_user:
>
> Can I:
>
> * View news...YES
> * List news ...YES
> * Post news...NO
> * Delete news...NO
> * Update news...NO
>
> * View Post...YES
>
> * View Private Post...YES
> * Create Post...NO
> * Update Post...NO
> * Delete Post...NO
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1093#issuecomment-122974157>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1093#issuecomment-122976113>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
Well if you take care of modifying the view, you can *safely* assume that the URL will work as expected…
thanks, L

On Jul 20, 2015, at 12:27 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:

I go into the views and changed the permissions there, but have not been
testing going to the url directly, I will add that to the list

On Mon, Jul 20, 2015 at 12:26 PM, Luca Cinquini <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Hi Sylvia,
> as I mentioned before, you also need to make sure that the “view” has the
> proper security check as well. I.e. if I am just a “user”, but someone told
> me the URL to create a POST, can I manually invoke it ? We need to make
> sure the answer is NO. Perhaps you are already doing this.
> thanks, L
>
> On Jul 20, 2015, at 12:21 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>
> <mailto:notifications@github.com>> wrote:
>
>
> Testing test_user:
>
> Can I:
>
> * View news...YES
> * List news ...YES
> * Post news...NO
> * Delete news...NO
> * Update news...NO
>
> * View Post...YES
>
> * View Private Post...YES
> * Create Post...NO
> * Update Post...NO
> * Delete Post...NO
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1093#issuecomment-122974157>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1093#issuecomment-122976113>
> .
>



--
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
Phone: 303-497-7753

**Comment by murphysj** [comment]
Contributor Role can:

    View news...YES
    List news ...YES
    Post news...YES
    Delete news...YES
    Update news...YES
    View Post...YES
    View Private Post...YES
    Create Post...YES
    Update Post...YES
    Delete Post...YES
    View file listing...YES
    View private file...YES
    Download private file...YES
    Add file...YES
    Update file...YES
    Delete file...YES
    View Resources...YES
    Add Resource Folder...YES
    Update Resource Folder...YES
    Delete Resource Folder...YES
    Add Resource...YES
    Update Resource...YES
    Delete Resource...YES
    Start a new Forum topic ... NO (admin only)
    Start a new Forum thread (private)...YES
    Start a new Forum thread (public)...YES
    Add a new Forum post...YES

**Comment by murphysj** [comment]
Tested locally. Not going to repeat on dev-hydra. closing.
