### ISSUE TITLE
Migrate CoG to new NOAA server, decomission hydra

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1103]
WHO: Luca

ESGF requires CENT OS 6. Need to upgrade hydra and dev-hydra.

**Comment by murphysj** [comment]
Eugene has agreed to wipe out dev-hydra and install centos. from there will install the stack. Ideally, we will then make this the machine for noaa.

**Comment by murphysj** [comment]
Eugene has wiped out dev-hydra and installed centos6. We now need to install the software stack on it.

**Comment by murphysj** [comment]
Next step is to make the new dev-hydra ... hydra.

**Comment by LucaCinquini** [comment]
New server installed on "esgf.esrl.noaa.gov" and content migrated as of last Thursday. Will now need to test and plan for final migration and switchover.

**Comment by LucaCinquini** [comment]
The migration has been completed, the new server esgf.esrl.noaa.gov was tested and is now operational.
