### ISSUE TITLE
Create template for ESGF/CoG home page

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1113]
Who: Luca

We decided it would be a good idea to have a template for the ESGF Node home page, which ESGF administrator can cut-and-paste into their wiki home page as a starting point, before applying site-specific customization.
Sylvia to create a first draft and then work with Dean, Renata, Matthew @ PCMDI.

**Comment by murphysj** [comment]
On a 8/27/15 telco, Dean, Jerry, and Robert agreed they are happy with the template.
