### ISSUE TITLE
Django upgrade

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1114]
Who: Luca

Upgrade Django to the latest version (currently 1.8.3), and at the same time resolve the warning that show up at startup.

**Comment by LucaCinquini** [comment]
First resolved warning:

WARNING:py.warnings:/usr/local/cog/venv/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/forms/models.py:1243: RemovedInDjango19Warning: cache_choices has been deprecated and will be removed in Django 1.9.

**Comment by LucaCinquini** [comment]
This is another common source of warning:

RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.

Unfortunately, this syntax is spread throughout the code - we will have to change it to request.GET/POST as we encounter it, and test that particular page right away.

**Comment by LucaCinquini** [comment]
The following replacement seems to be working, for example when retrieving the parameter 'next':

from:
_next = request.REQUEST.get('next', None)
to:
_next = request.GET.get('next', None) or request.POST.get('next', None)

**Comment by LucaCinquini** [comment]
Note that I have upgraded the dependency to Django 1.8.3 - Sylvia you might need to reinstall the whole virtual environment.

**Comment by murphysj** [comment]
Joy

On Mon, Aug 17, 2015 at 2:25 PM, Luca Cinquini <notifications@github.com>
wrote:

> Note that I have upgraded the dependency to Django 1.8.3 - Sylvia you
> might need to reinstall the whole virtual environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1114#issuecomment-131949542>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
@LucaCinquini 

What is the difference between this ticket and #979, which also was a django upgrade and was two releases ago in 2.13?  Did we upgrade again?

**Comment by LucaCinquini** [comment]
This is upgrading to yet another minor django version, and at the same time work on some of the deprecation warnings.

**Comment by murphysj** [comment]
Luca and I decided not to track all the warnings in this ticket but ticket them separately as we find them. 
There fore I am closing this ticket since I have verified the new installation script installs django 1.8.3.
