### ISSUE TITLE
Login and Create Account URL keep expanding

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1116]
Who: Luca

The Login and Create Account URL are meant to return the users to the original page, after they have logged in or created an account. The return-to-url is saved into the '?next=" parameter.
Problem is, right now the parameter value keep expanding if those links are clicked multiple times. For example:

http://cog-esgf.esrl.noaa.gov/login/?next=http://cog-esgf.esrl.noaa.gov/login/?next=http://cog-esgf.esrl.noaa.gov/projects/esgf-esrl/
or:
http://cog-esgf.esrl.noaa.gov/user/add/?next=http://cog-esgf.esrl.noaa.gov/login/?next=http://cog-esgf.esrl.noaa.gov/login/?next=http://cog-esgf.esrl.noaa.gov/projects/esgf-esrl/

**Comment by LucaCinquini** [comment]
Problem is solved. Now the return-to-url will only contain one value, which is the very original page where the user started to click on those links.

**Comment by murphysj** [comment]
verified on cu dev closing
