### ISSUE TITLE
Can't delete external URLs

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1118]
WHO: Sylvia

Found in 2.14 at CU and NOAA.

**Comment by LucaCinquini** [comment]
Sigh, this is a consequence of a non-backaward compatible change in Django 1.7:

Changed in Django 1.7:
If you call formset.save(commit=False), objects will not be deleted automatically. You’ll need to call delete() on each of the formset.deleted_objects to actually delete them:

>>> instances = formset.save(commit=False)
>>> for obj in formset.deleted_objects:
...     obj.delete()

**Comment by LucaCinquini** [comment]
This is now fixed for external URLs form sets (see view_external_urls.py) but the same behavior could show up in any other view that uses form sets with commit=False.
Sylvia, could you please check in the code if we do this for any other page ?

**Comment by murphysj** [comment]
Found two places that needed to be fixed. Added the explicit deletion code. 
* impacts_update
* user_update (URLs)

should not need fix:
* user_update (openIDs) (don't think user can delete these...)

don't know about:
* _imageformset_update

**Comment by LucaCinquini** [comment]
Thanks. If you check the final result (wether you can delete or not the objects) you should be able to tell wether the code needs fixing or not.
L

On Aug 24, 2015, at 1:33 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Found two places that needed to be fixed. Added the explicit deletion code.

  *   impacts_update
  *   user_update (URLs)

should not need fix:

  *   user_update (openIDs) (don't think user can delete these...)

don't know about:

  *   _imageformset_update

**Comment by murphysj** [comment]
I did for the ones I updated. I have no idea how imageformset_update is
being used. It could be all over the place. Is is partner and sponsor
images?

On Mon, Aug 24, 2015 at 1:51 PM, Luca Cinquini <notifications@github.com>
wrote:

> Thanks. If you check the final result (wether you can delete or not the
> objects) you should be able to tell wether the code needs fixing or not.
> L
>
> On Aug 24, 2015, at 1:33 PM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> Found two places that needed to be fixed. Added the explicit deletion code.
>
> * impacts_update
> * user_update (URLs)
>
> should not need fix:
>
> * user_update (openIDs) (don't think user can delete these...)
>
> don't know about:
>
> * _imageformset_update
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1118#issuecomment-134349737>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1118#issuecomment-134356025>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
I dunno either - we’ll have to research…
thanks, L

On Aug 24, 2015, at 1:55 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:

I did for the ones I updated. I have no idea how imageformset_update is
being used. It could be all over the place. Is is partner and sponsor
images?

On Mon, Aug 24, 2015 at 1:51 PM, Luca Cinquini <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Thanks. If you check the final result (wether you can delete or not the
> objects) you should be able to tell wether the code needs fixing or not.
> L
>
> On Aug 24, 2015, at 1:33 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>
> <mailto:notifications@github.com>> wrote:
>
>
> Found two places that needed to be fixed. Added the explicit deletion code.
>
> * impacts_update
> * user_update (URLs)
>
> should not need fix:
>
> * user_update (openIDs) (don't think user can delete these...)
>
> don't know about:
>
> * _imageformset_update
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/1118#issuecomment-134349737>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1118#issuecomment-134356025>
> .
>



--
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
Phone: 303-497-7753

**Comment by murphysj** [comment]
tested external URLs on cu test. they are working

**Comment by murphysj** [comment]
tested impacts on cu test. they are NOT working.
