### ISSUE TITLE
Add "secure" attribute to all sensitive cookies

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1123]
Who: Luca

JPL App Scan identified this "medium" security vulnerability:

Basically the only required attribute for the cookie is the "name" field. Common optional attributes are: "comment", "domain", "path", etc.
The "secure" attribute must be set accordingly in order to prevent to cookie from being sent unencrypted.

RFC 2965 states:
"The Secure attribute (with no value) directs the user agent to use only (unspecified) secure means to contact the origin server whenever it sends back this cookie, to protect the confidentially and authenticity of the information in the cookie."

**Comment by LucaCinquini** [comment]
This has been implemented through a new flag that is read from the usual cog_settings.cfg file:
PRODUCTION_SERVER = True
will cause the SESSION and CSRF cookie to be sent only if the connection is secure (i.e. uses HTTPS).
For the development instances (that typically do not run under SSL), this flag should be set to False.
Please NOTE: add this flag manually to your cog_settingt.cfg file after you git pull from the repo.

**Comment by murphysj** [comment]
@LucaCinquini 

How do I test this?

**Comment by murphysj** [comment]
Actually, 
I tested this locally by accident because after upgrading I could no longer login until i set PRODUCTION_SERVER to True. 

Closing.
