### ISSUE TITLE
Fix help text in search configuration page

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1139]
Who: Sasha

The default behavior of the CoG Search page is to return non-replicas only, which is not what s expected from the help text in the search configuration page (which indicates the default is to search for ALL replicas).

**Comment by LucaCinquini** [comment]
Sasha is correct. CoG default behavior is to (see SolrSearchService class):

o if the user does not specify anything, set replica=false (i.e. only return non replicas. Note that instead the ESGF search service default is to NOT set the replica flag, so return replica+non-replicas)

o if the user does not specify anything, do NOT set the latest flag (i.e. return latest+older versions, consistent with the ESGF search service default)

o if  the user does not specify anything do NOT set the distrib flag (and consequently use the ESGF default which is distrib=true) 

Any change in CoG from this behavior is luckily going to introduce bugs, so I wouldn't change it. I did fix the help text in the admin page for configuring the search to reflect the behavior above.

**Comment by murphysj** [comment]
Good catch. I never realized the text associated with the replicas checkbox on the search configuration page was incorrect. The new text is much better. 

verified on cu-dev. closing.
