### ISSUE TITLE
Fix request.REQUEST in membership_process (in membership.py)

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1140]
WHO:Sylvia

This function will need to be split into a GET and POST section.

**Comment by murphysj** [comment]
@LucaCinquini 

Did you get this instance of request.REQUEST in your recoding blitz? If so i will close this as a duplicate.

**Comment by LucaCinquini** [comment]
Yes it should be fixed there as well as in many other places.
thanks, L

**Comment by murphysj** [comment]
THis has been replaced by #1194, which covers all such syntax. Closing this as a duplicate.
