### ISSUE TITLE
Add "special notification" block 

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1147]
WHO: Sylvia

Would be a great place for things like down times, data unavailability etc.

**Comment by LucaCinquini** [comment]
I'm not sure it would very visible there - I would think that an optional front-page banner would be more useful.

**Comment by murphysj** [comment]
This may be true, but what we have received two support requests just today
about where is CMIP5 data and there are banners on all the relevant nodes.
They still are emailing us.

Just a thought anyway.

On Tue, Sep 29, 2015 at 2:11 PM, Luca Cinquini <notifications@github.com>
wrote:

> I'm not sure it would very visible there - I would think that an optional
> front-page banner would be more useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1147#issuecomment-144177999>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
During the 10/6/15 CoG call, we decided to make this 

a) a node-wide notification
b) controlled by the template override system that is already in place

Sylvia will first mock up something.

**Comment by murphysj** [comment]
First draft
![cog_mockup_151008_node_notification](https://cloud.githubusercontent.com/assets/1512704/10377623/a6d66264-6dc1-11e5-95f1-5f210a24c1d8.png)

**Comment by murphysj** [comment]
Both L and C like it. Time to code it for real.

**Comment by murphysj** [comment]
block created in layout_baseline.html
template created in /common, with visibility hidden
override tested 
downtime example added to Resources

**Comment by murphysj** [comment]
verified on cu dev.
closing
