### ISSUE TITLE
Center the User Profile table

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1164]
Who: Luca

The user profile table at:
https://www.earthsystemcog.org/user/detail/621/
should probably be centered under the orange banner ? (not the full page extent)

**Comment by murphysj** [comment]
Actually, the banner needs to go across the entire page with the table
centered under it.

On Tue, Nov 3, 2015 at 9:10 AM, Luca Cinquini <notifications@github.com>
wrote:

> Who: Luca
>
> The user profile table at:
> https://www.earthsystemcog.org/user/detail/621/
> should probably be centered under the orange banner ? (not the full page
> extent)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1164>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
That would work too.
thanks, L

On Nov 3, 2015, at 9:12 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:

Actually, the banner needs to go across the entire page with the table
centered under it.

On Tue, Nov 3, 2015 at 9:10 AM, Luca Cinquini <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Who: Luca
>
> The user profile table at:
> https://www.earthsystemcog.org/user/detail/621/
> should probably be centered under the orange banner ? (not the full page
> extent)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1164>.
>



--
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
Phone: 303-497-7753

**Comment by murphysj** [comment]
@LucaCinquini 

Actually, 
This page was already modified as part of the expansion to 1140px. The yellow banner looks ok, but the table needs to be moved over 40px. I am still working on making sure all the pages look ok at 1140.

![user_node](https://cloud.githubusercontent.com/assets/1512704/10918571/aa4b0956-8223-11e5-9c15-e52c001e47ee.png)

**Comment by murphysj** [comment]
cecelia wanted this table left justified with other elements on the page when present.

**Comment by murphysj** [comment]
We have two options now, centered:
![user_node](https://cloud.githubusercontent.com/assets/1512704/10977428/3e469536-83ae-11e5-9af6-951356c4fde5.png)

And aligned to the left
![admin_table](https://cloud.githubusercontent.com/assets/1512704/10977465/76f300e0-83ae-11e5-8a11-1c3dd4435bf4.png)

**Comment by murphysj** [comment]
First changed verified on cu dev

Second was verified locally. Will have to double check during the release since there are no local accounts on cu-dev.
