### ISSUE TITLE
Use PNGs for thumbnails

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1165]
Who: Luca

Up so far we have created image thumbnails as JPEG. Unfortunately, JPEG requires additional libraries to be installed on the system, and may break when the python installation is upgraded. Better switch to using PNG which are supported more uniformly.

**Comment by LucaCinquini** [comment]
Done, user thumbnails re now created as PNGs.

**Comment by murphysj** [comment]
@LucaCinquini 
Has this been merged with CSS cuz I just tested and I can upload a jpg and it stays a jpg

**Comment by LucaCinquini** [comment]
The picture should stay a JPEG, but the generated thumbnail should be a png.
I just remerged and pushed now, you could try again.
thanks, L

On Nov 5, 2015, at 11:29 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucaCinquini<https://github.com/LucaCinquini>
Has this been merged with CSS cuz I just tested and I can upload a jpg and it stays a jpg

**Comment by murphysj** [comment]
@LucaCinquini 
Did a pull on CSS. If the profile image is a png, it shows up in the people listing. If it is a jpg, it does not, so the conversion may not be working. I did do a full reinstall.

**Comment by LucaCinquini** [comment]
Well you are right. It turns out that processing jpeg images depends on a bunch of optional libraries, which need to be installed differently on different OSs. Rather than depending on complex installation procedures, I changed the CoG software such that, if an error arises when creating a reduced JPEG image, the full image is used instead. This seems to be working just fine - the only drawback being that the server is sending a bigger file to the client. Oh well...

**Comment by murphysj** [comment]
Does this mean that the people page will display the larger image? Cecelia
won't for that.

On Mon, Nov 9, 2015 at 5:10 AM, Luca Cinquini <notifications@github.com>
wrote:

> Well you are right. It turns out that processing jpeg images depends on a
> bunch of optional libraries, which need to be installed differently on
> different OSs. Rather than depending on complex installation procedures, I
> changed the CoG software such that, if an error arises when creating a
> reduced JPEG image, the full image is used instead. This seems to be
> working just fine - the only drawback being that the server is sending a
> bigger file to the client. Oh well...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1165#issuecomment-155047423>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
No, the image should be constrained in size.
L

On Nov 9, 2015, at 8:09 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:

Does this mean that the people page will display the larger image? Cecelia
won't for that.

On Mon, Nov 9, 2015 at 5:10 AM, Luca Cinquini <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Well you are right. It turns out that processing jpeg images depends on a
> bunch of optional libraries, which need to be installed differently on
> different OSs. Rather than depending on complex installation procedures, I
> changed the CoG software such that, if an error arises when creating a
> reduced JPEG image, the full image is used instead. This seems to be
> working just fine - the only drawback being that the server is sending a
> bigger file to the client. Oh well...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1165#issuecomment-155047423>
> .
>



--
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
Phone: 303-497-7753

**Comment by murphysj** [comment]
luca and I tested this together
