### ISSUE TITLE
Improve configuration of peer nodes

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1166]
Who: Luca

We should improve the process for updating the list of available ESGF/CoG peers

**Comment by LucaCinquini** [comment]
Now CoG reads the list of peer nodes from an ESGF configuration location: /esg/config/esgf_cogs.xml
This list is read every time CoG is restarted, or it can be reloaded by using the command:
python manage.py sync_sites
The latest version of the file should be downloaded separately from the ESGF GitHub repo (by the installer ?). If the file is not found, it will be skipped.

**Comment by LucaCinquini** [comment]
Sylvia you can test this ticket by downloading the file:
https://github.com/ESGF/config/blob/master/esgf-prod/esgf_cogs.xml
and reference it appropriately in your cog_settings.cfg configuration:
PEER_NODES=/path/to/your/esgf_cogs.xml

**Comment by murphysj** [comment]
Tested by doing the above. Could turn on the nodes widget and see the new peers and get a peer sync report. So that is working.
