### ISSUE TITLE
Make roll-up accordions open by default

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1167]
WHO: Cecelia

People are not seeing the roll-up

**Comment by murphysj** [comment]
@LucaCinquini 
Can't find what controls this. You may have to do it.

**Comment by LucaCinquini** [comment]
It's the style="display:block" or style="display:none" attribute in the page rollup.html.
I have committed the change to open the rollups by default, but I have to admit I think it looks ugly. If we keep it this way, we might want to change the text in the header from "View peer something" to "Close peer something". More ugliness.

**Comment by murphysj** [comment]
we rolled this back. no longer applicable.
