### ISSUE TITLE
Enable OpenID selector

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1168]
Who: Phil Kershaw

Phil Kershaw and the ESGF security team asked that we enable OpenID selector on the CoG login page, 
to facilitate the user experience, and to provide a path forward for switching to openID-Connect base authentication.

**Comment by LucaCinquini** [comment]
This is now done, controlled by the init() function in cog/templates/cog/openid/login.html

Note that:
a) selecting open ids from hydra is now NOT allowed because hydra is still running the old ESGF software stack
b) login as "rootAdmin" does not currently work because of some bug in the ESGF software stack, which is under investigation

Must review the text on the page to say something like "To login, please select the site where you first registered to login in with your username and password, or entered your full openid below".

**Comment by LucaCinquini** [comment]
It turns out b) is actually not an ESGF bug, it was due to the fact that there were two users in the JPL ESGCET database with username="rootAdmin", one of which had password=null.

**Comment by murphysj** [comment]
@LucaCinquini 

How does this manifest? Not seeing anything locally. Is this the ESGF pull down openID?

**Comment by LucaCinquini** [comment]
Yes you need to have a file called /esg/config/esgf_known_providers.xml for any selection to show up.
I will demo it tomorrow at the usual call.
thanks, L

On Nov 9, 2015, at 8:26 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucaCinquini<https://github.com/LucaCinquini>

How does this manifest? Not seeing anything locally. Is this the ESGF pull down openID?

**Comment by murphysj** [comment]
@LucaCinquini 

Just checking...I assume we will have to upgrade NOAA to the latest ESGF stack as part of this release in order to get hydra to work?

**Comment by murphysj** [comment]
Seems to work. will know more after the release.
