### ISSUE TITLE
Changes to account do not propogate to the ESGF IdP database 

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1169]
Who: Luca

Right now, if a user uses the 'Update Profile' facility on CoG to update their information, those changes will NOT be propagated to the corresponding esgcet database, which backs up the IdP. Instead, they should be.

Note that once the changes are in the IdP, at least those fields that are exchanged via OpenID AX (i.e. first name, last name, username, email) will be propagated to the other CoGs the next time the user logs in, because of the setting:

OPENID_UPDATE_DETAILS_FROM_SREG = True

**Comment by LucaCinquini** [comment]
This is now implemented: when a user updates their profile on CoG, the following fields are updated in the ESGF database: first name, last name, email, organization, city, state, country.

**Comment by murphysj** [comment]
@LucaCinquini 

Can't test since I don't have an ESGF IdP.
