### ISSUE TITLE
Prevent bad characters in project short and long names

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1170]
Who: Luca

If a project short or long name contains non-conventional characters (such  as "la nina"...), the inter-cogs synchronization crashes. Other parts of the code might have problems as well. Must validate input when the project is first created.

**Comment by LucaCinquini** [comment]
The project short name was already protected against this as it can only contain letters, numbers, '-' and '_'. I am now checking the project long name to only contain ascii characters.

**Comment by murphysj** [comment]
verified on cu dev that short names are prohibited from having special characters.

**Comment by murphysj** [comment]
@LucaCinquini 
Did you actually complete this? Are the special characters no allowed in the long_name?

**Comment by LucaCinquini** [comment]
The only ASCII character that is NOT allowed in project long names is the quote (").
Additionally, no non-ASCII characters are allowed in neither project long names or  short names.

**Comment by murphysj** [comment]
@LucaCinquini 

I successfully tested the quotation marks, but non-ascii characters were allowed in long_names. 

Look at: https://cog-cu-dev.colorado.edu/projects/ams_wrc/ 

Look at the update project page. 

Perhaps you mean something else by non-ascii?

**Comment by LucaCinquini** [comment]
If you mean:

AMS Water Resources Committee &#167;

those I think are ASCII characters. The non-asci characters are for example 

ã ñ

etc.

**Comment by murphysj** [comment]
copying a non-ascii character from a web page into a form works for testing. 
verified on cu-dev. closing.
