### ISSUE TITLE
Local search must include replicas

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1173]
Who: Dean

Dean suggested that the radio button "Search Local Site" should also return replicas at that site, otherwise users will be getting confused.

**Comment by LucaCinquini** [comment]
Issue was discussed at the 2016/03/01 ESGF conference call, and it seems like there was general agreement to do this.

**Comment by LucaCinquini** [comment]
This is now implemented: when the "local" check box is checked, the search automatically span all replicas. Additionally, checking any of the check boxes automatically triggers the search (restarting from search result number 1).

**Comment by murphysj** [comment]
@LucaCinquini 

How can you tell what is a replica and what is not? 

How can I test this?

**Comment by LucaCinquini** [comment]
Hi Sylvia,
	you can try to configure the search to use “lcmdi.llnl.gov” as the primary index node
and verify that clicking on “local search” returns way more datasets than a distributed search, with no replicas, where the facet index_node=pcmdi is selected.
thanks, L

**Comment by murphysj** [comment]
@LucaCinquini I configured the search with pcmdi, that node does not exist in the list of available nodes in the faceted pull down. What controls that? I tried syncing peers with pcmdi, but that did not affect things.

**Comment by LucaCinquini** [comment]
Not sure I follow: PCMDI is the correct server, GitHub had auto-corrected it. The available servers for "index_node" come directly from the search results...

**Comment by murphysj** [comment]
actually the index to search for is called aimes3 not pcmdi.
verified on cu dev
closing
