### ISSUE TITLE
Deleting someone from a project does not delete them from roles

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1175]
WHO: Sylvia

Kathy Saint is no longer a member of the ESMF project but she still shows up as a organizational body member visually.

Also, can't delete her, why?

**Comment by LucaCinquini** [comment]
Now when a user is removed from all roles for a project (User, Contributor, Admin), he/she is also removed from amy governance roles associated with the project: Management Bodies, Communication Means, Organizational Roles.

**Comment by LucaCinquini** [comment]
As for removing Kathy from ESMF, I think you need to:

a) change your email to something invalid, so she doesn't receive notifications
b) add her back to ESMF as a User
c) remove her from ESMF, which will remove her from all ESMF governance

Off course, after the software has been upgraded to this release.

**Comment by murphysj** [comment]
verified on cu dev
