### ISSUE TITLE
Deleting an account does not delete the reference in the ESGF IdP database

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1179]
WHO: Sylvia

Found in testing account deletion.

**Comment by LucaCinquini** [comment]
Now, the CoG admin page "List System Users" has an additional column "Delete Account". This link leads to a page that allows to delete a user account, including:
a) all related CoG objects (user, user profile, data cart, openid, group memberships in CoG projects)
b) the related ESGF user object and associated access control permissions

**Comment by murphysj** [comment]
@LucaCinquini 
Can't test since I don't have an ESGF IdP.
