### ISSUE TITLE
Prevent the creation of wiki urls that match templated urls

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1183]
WHO: Sylvia

In cleaning up orphened posts, I found that there is nothing prohibiting the creating of a wiki url that matches a templated page. 

If a user does that, they won't be able to find or delete there page because it will always redirect to the templated version.

**Comment by LucaCinquini** [comment]
For example we should not allow people to create a wiki page with URL:
/projects/cog/forum/

**Comment by LucaCinquini** [comment]
Done, check is in PostForm.clean()

**Comment by murphysj** [comment]
spot checked on cudev with roles, forum, user_docs, and metrics. 

closing.
