### ISSUE TITLE
Bug in "You are a project member" display in upper right bar

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1184]
Who: Luca

It has been (correctly) noted that the message "You are a project member" in the upper right bar shows up only id the user has "User" role - not if he/she has "Contributor" or "Admin" role.

**Comment by LucaCinquini** [comment]
Fixed.

**Comment by murphysj** [comment]
verified on cu dev by making an account have a user, then contrib_user, then admin_user profile. In all three instances the welcome message appeared.
