### ISSUE TITLE
Ensure links to CMIP5 metadata work when ESGF comes back online

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1185]
WHO: Hans Ramthum

On the 12/14/15 ES-DOC telco, Hans asked if the ESGF dataset to ES-DOC metadata links would work with the new ESGF software stack.

As soon as ESGF is back online, we need to check this AND make sure CoG is using the latest version of the API to link to ES-DOC metadata.

**Comment by murphysj** [comment]
This is the code that starts the workflow:

    
      {% if project.searchprofile.modelMetadataFlag %}
         [ <a href="#" onClick="onDatasetClicked('{{record.fields.project.0}}', '{{record.fields.instance_id.0}}')"><strong>Model Metadata</strong> </a> ]
      {% endif %}

**Comment by murphysj** [comment]
The javascript function referenced above is located in /cog/common/cim.html

    // function triggered by clicking on a ESDOC dataset link
	function onDatasetClicked(project, dataset) {
            load_cim_libraries(function() {
                ESDOC.viewer.renderFromExternalID( {
                    project : project,
                    externalID : dataset,
                    externalType : 'dataset'
		});
            });
	}

**Comment by murphysj** [comment]
The question is whether this function is correct now that esdoc has changed how it does stuff. #1204 is looking into that file and whether the code there is deprecated.

**Comment by murphysj** [comment]
@LucaCinquini 

FYI, 
Mark recommends the following:
Yes this is correct invocation of the plugin. However you should realise that nowadays the plugin simply constructs a URL to the viewer & opens the constructed URL in a new browser tab. You may wish to replace this code with code to perform the URL construction yourselves. This is what the ISENES portal now does. For example the IPSL model is listed on the following page: https://verc.enes.org/models/earthsystem-models/ipsl/ipslesm. The links to the documentation served by ES-DOC viewer are constructed by the ISENES Verc portal and thus they do not rely upon the plugin. For example: http://view.es-doc.org/?renderMethod=name&type=cim.1.software.ModelComponent&name=IPSL-CM5A-LR&project=CMIP5. So to summarise: the COG code is fine but it could be updated to remove dependency upon the plugin altogether.

**Comment by murphysj** [comment]
/cog/common/cim.html can still be the location to contain this code. I would move it out of common though and put it under search.

**Comment by murphysj** [comment]
Just tested this with a CMIP5 dataset in FF and Safari. Nothing happens when you click the link.

Here is the current code:

    [ <a href="#" onClick="onDatasetClicked('CMIP5', 'cmip5.output1.IPSL.IPSL-   CM5A-LR.abrupt4xCO2.3hr.land.3hr.r9i1p1.v20110921')"><strong>Model Metadata</strong> </a> ]

    
    <div class="padded-box" id="dataset_cmip5.output1.IPSL.IPSL-CM5A-LR.abrupt4xCO2.3hr.land.3hr.r9i1p1.v20110921|esgf.extra.cea.fr" style="display:none; width:500px;">

**Comment by murphysj** [comment]
There are two unterminated lines in the main load function
css_link.setAttribute("href",CSS_PATH)

                var first_script = document.getElementsByTagName("script")[0]

**Comment by LucaCinquini** [comment]
I removed the old code and inserted instead links to the ES-DOC viewer. This functionality is enabled only for CMIP5 datasets for now.

**Comment by murphysj** [comment]
tested on cu-dev closing
