### ISSUE TITLE
Generate random SECRET_KEY when CoG is first installed

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1189]
Who: Jasaun Neff

Jasaun has reviewed the CoG code and suggested that when CoG is first installed, a new random secret key is generated which is unique to each site. This will avoid having CoG deployed with the same default secret key if administrators forget to change it.

**Comment by LucaCinquini** [comment]
Done, new random secret key generated with length of 128 characters when CoG is first installed.

**Comment by murphysj** [comment]
@LucaCinquini 
How would I test this?

**Comment by LucaCinquini** [comment]
I think you can remove the SECRET_KEY entry from cog_config/cog_settings.cfg
and rerun “python setup.py setup_cog”
to see a new SECRET_KEY be inserted in the file
L

**Comment by murphysj** [comment]
Ok, once I can setup :) I will try that.

On Mon, Jan 11, 2016 at 12:25 PM, Luca Cinquini <notifications@github.com>
wrote:

> I think you can remove the SECRET_KEY entry from
> cog_config/cog_settings.cfg
> and rerun “python setup.py setup_cog”
> to see a new SECRET_KEY be inserted in the file
> L
>
> On Jan 11, 2016, at 12:23 PM, Sylvia Murphy <notifications@github.com>
> wrote:
>
> > @LucaCinquini
> > How would I test this?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1189#issuecomment-170661857>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
locally, i deleted the secret_key line from my config file and installed cog. A new secret key was generated in the file. 

I did it again just to make sure the *same* key was not generated. It was not.

closing.
