### ISSUE TITLE
Remove legacy code related to system-paths based authorization

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1190]
Who: Jasaun Neff

There seems to be code that establishes authorization for file uploads based on comparing user supplied paths to system paths. This code is susceptible to attacks if strange characters or symlinks are used. Code is located in function file browser_check() in file cog/cog_filebrowser.py, which is invoked by file browser/sites.py in many places.

**Comment by LucaCinquini** [comment]
The code has been commented out since we don't think it's used anymore. If a problem arises, we will revisit the code and fix it as Jasaun suggested,

**Comment by murphysj** [comment]
Conducted a code review. I see the code commented out AND the extra message indicating that it was invoked so we can tell if the code gets there somehow. A few releases from now we should remove this code all together.
