### ISSUE TITLE
Abide to django deprecation warning about request.REQUEST

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1194]
Who: Luca

Currently, many of the CoG views throw the following warning:

RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.

We need to avoid using request.REQUEST everywhere before upgrading to django 1.9+. Also, some of the third party libraries use the same construct and will have to be upgraded.

**Comment by LucaCinquini** [comment]
A utility function cog.views.getQueryDict() has been written that can be used instead of the request.REQUEST construct. This function has been invoked in the following views:

o cog.views.views_membership.membership_process()

**Comment by LucaCinquini** [comment]
The following packages still use request.REQUEST:

o django-pagination

WARNING:py.warnings:/Library/Python/2.7/site-packages/django_pagination-1.0.7-py2.7.egg/pagination/middleware.py:7: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  return int(self.REQUEST['page'])

**Comment by LucaCinquini** [comment]
The issue with django-pagination has been moved to a different ticket:
https://github.com/EarthSystemCoG/COG/issues/1195

The django issuen should fix itself with upgrading django....

**Comment by murphysj** [comment]
Conducted a code review. Could not find any request.REQUEST syntax anywhere.
