### ISSUE TITLE
Remove dependency on django-pagination

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1195]
Who: Luca

Currently, CoG uses django-pagination every time there are too many objects to be displayed on one page. Unfortunately, django-pagination is 5 years old and not maintained any more. It will not be compatible with django 1.9+ because it uses the request.REQUEST object that will be supported any longer.

We can instead switch CoG to use the Django "Paginator" object.

**Comment by LucaCinquini** [comment]
The following pages have been updated to use the django Paginator object:

o /cogadmin/projects/

Dependency on django-pagination has been removed.

**Comment by murphysj** [comment]
I made a slight mod to _pagation.html. I replaced # with Number. We may need to tweak the cosmetics of this a bit more. We'll see what C has to say. For now closing.
