### ISSUE TITLE
Patch django-openid-auth for Django upgrade to 1.9.1

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1198]
Who: Luca

We currently use django-openid-auth 0.5 for ESGF openid authentication. There is a newer version 0.7 which we should use. Unfortunately, even the newer version suffers from deprecation warnings related to the django construct request.REQUEST. We need to fix these warnings if we want to upgrade to django 1.9 and still support openid authentication.

**Comment by murphysj** [comment]
@LucaCinquini 

I assume this was done since we have both run the setup.py script on the separate openid directory?

**Comment by LucaCinquini** [comment]
Yes - a patched version of django-openid-auth has been uploaded to:

https://github.com/EarthSystemCoG/django-openid-auth

and must now be separately installed, manually.
