### ISSUE TITLE
Remove PIL, upgrade Pillow

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1199]
Who: Luca

We should stop installing PIL and instead just use its new replacement Pillow

**Comment by LucaCinquini** [comment]
Done: setup.py does not contain any PIL dependency any more, rather it contains the most up to date Pillow library 3.1.0.
Note that to work on MacOSK, Pillow must be installed manually through wheel as a pre-requisite:

pip install wheel
pip install --use-wheel Pillow==3.1.0

**Comment by murphysj** [comment]
I know that PIL is gone because we had to jump through hoops to get it back when we could not get the install working on my mac.
