### ISSUE TITLE
Upgrade Django version to 1.9.1

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1200]
Who: Luca

This version of CoG will use the latest Django version 1.9.1

**Comment by LucaCinquini** [comment]
As part of this upgrade, the following django apps also need to be upgraded:

o django-grappelli==2.7.2
o django-contrib-comments==1.6.2

**Comment by LucaCinquini** [comment]
The following libraries did not need to be upgraded, but were upgraded nonetheless:

o sqlalchemy==1.0.11

**Comment by murphysj** [comment]
Did a code review of setup.py and see the change to 1.9.1. I did deploy this on cudev too and it worked there.
