### ISSUE TITLE
delete cim.html?

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1204]
WHO: Sylvia

This looks like the old way to invoke the CIM. Investigate and delete if necessary.

**Comment by murphysj** [comment]
@allynt 

Can you tell by looking at this file: https://github.com/EarthSystemCoG/COG/blob/master/cog/templates/cog/common/cim.html

Whether this is the old, deprecated, way of hooking into the CIM viewer?

We still need to connect ESGF datatsets to esdoc, but these don't seem to be old and I know stuff evolved a lot.

**Comment by allynt** [comment]
I recognize this code as my own.  The calls to "renderFromExternalID" and "renderFromName" still look valid according to the latest es-doc content.  I am double-checking w/ Mark and will confirm ASAP.

Recall that this script was written to get around SSL restrictions of loading external static content.

**Comment by allynt** [comment]
According to Mark:

>Yes this is correct invocation of the plugin.  However you should realise that nowadays the plugin simply constructs a URL to the viewer & opens the constructed URL in a new browser tab.  You may wish to replace this code with code to perform the URL construction yourselves.  This is what the ISENES portal now does.  For example the IPSL model is listed on the following page: https://verc.enes.org/models/earthsystem-models/ipsl/ipslesm.  The links to the documentation served by ES-DOC viewer are constructed by the ISENES Verc portal and thus they do not rely upon the plugin.  For example:  http://view.es-doc.org/?renderMethod=name&type=cim.1.software.ModelComponent&name=IPSL-CM5A-LR&project=CMIP5.  So to summarise: the COG code is fine but it could be updated to remove dependency upon the plugin altogether.

**Comment by murphysj** [comment]
So we keep the file but may update what is in it. We have a separate ticket #1185, to make sure this all works.
