### ISSUE TITLE
Assigning a User to the Contributor's Group does not work from the Pending Users page

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1210]
WHO: Sylvia

Try this...

a) Create a new test account
b) Login as that account
c) Join a project
d) Login in as the project admin
e) Go to the pending user's page
f) Accept the test account as a Contributor

Nothing happens

If you accept the user as a User, then the form clears out.

**Comment by murphysj** [comment]
@LucaCinquini 

Here are the two filters to determine whether or not a user is a member of a project. Note that the first filter includes all roles, the second filter only lists users. I am thinking that if someone requests a membership, which defaults to the User Group, but is granted a Contributor group the function will fail and say they are still pending....

# filter to determine whether a user belongs to a project
@register.filter
def hasUser(project, user):
    return project.hasUser(user)

# filter to determine whether a user is pending approval in a project
@register.filter
def hasUserPending(project, user):
    return project.hasUserPending(user)

# returns true if the user is enrolled in any of the project's groups
def hasUser(self, user):
    if user in self.getUserGroup().user_set.all():
        return True
    elif user in self.getContributorGroup().user_set.all():
        return True
    elif user in self.getAdminGroup().user_set.all():
        return True
    else:
        return False
    
# return true if the user is waiting membership approval in the project's 'user' group
def hasUserPending(self, user):
    mrlist = MembershipRequest.objects.filter(group=self.getUserGroup()).filter(user=user)
    if len(mrlist) > 0:
        return True
    else:
        return False

**Comment by murphysj** [comment]
Rocky is seeing:

He is listed as a Contributor and Admin on coupledNEMS, but his welcome message is saying he is still waiting for project membership.

**Comment by murphysj** [comment]
@LucaCinquini 

My test for this functionality starts from the All Node Users page. This seems to work ok.

**Comment by LucaCinquini** [comment]
It seems to work ok for me... We can perhaps talk tomorrow...

**Comment by murphysj** [comment]
I will demo it. Rocky has reported it. He is listed as both a pending user
and an accepted user on that project.

On Wed, Jan 20, 2016 at 4:39 PM, Luca Cinquini <notifications@github.com>
wrote:

> It seems to work ok for me... We can perhaps talk tomorrow...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1210#issuecomment-173403594>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
Actually, on further inspection, it was really a bug. The problem was that when a user was enrolled in the Contributor or Admin group, his/her membership request with the User group was NOT removed.
Now that happens: when a user is enrolled in ANY group for a project, all membership requests for that user, project are removed.

**Comment by LucaCinquini** [comment]
To fix the problem for Rocky, you just need to click the "Submit" button on the Pending Users page for that project - once the patch releases has been deployed at NOAA.

**Comment by murphysj** [comment]
Tested after release. Working now.
