### ISSUE TITLE
Incorrect redirection after logout

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1211]
Who: Sylvia

If a user is logged into a page that requires special privileges to view, such as project administrator or site administrator, and logs out, he/she is redirected to the same page, and then to the wrong LOGIN url.

**Comment by LucaCinquini** [comment]
This issue was caused by incorrect LOGIN_URL in settings.py, which was lacking a trailing '/'.
Now fixed.

**Comment by murphysj** [comment]
Tested after release. Closing.
