### ISSUE TITLE
Investigate Postgres's new row level security

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1212]
WHO: Ben
Postgres now has a way to add extra security to just select rows in a table. Ben thought this might be a good way to protect our passwords. 

http://www.postgresql.org/docs/devel/static/ddl-rowsecurity.html

Is this worth doing?

**Comment by LucaCinquini** [comment]
Password are already encrypted inside Postgres... And if anybody steals a password, the only thing they can do is impersonate a CoG  user. I don't think this is really needed.

**Comment by murphysj** [comment]
sounds good. thanks for looking into it.
