### ISSUE TITLE
Be able to turn off the federation of select projects

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1213]
WHO: ESGF

ESGF node admins want to be able to have local projects such as CMIP5-DKRZ. We would not want these shared across the federation because they would confuse users. 

We need a way to choose what projects to share.

**Comment by LucaCinquini** [comment]
This is now implemented. A project has a new "shared" field which by default is True. When a project is shared, it is visible to all other federated CoGs, when it is not shared, it is not.

Behind the scenes, each CoG always includes all ACTIVE projects (shared and not, private and not) in the list of projects it advertises to all other CoGs. But other CoGs do not include not-shared projects in the project browser widget. This way, a project can be switched from shared to not-shared and vice versa, and the other CoGs will update its settings appropriately the next time they execute a synchronization.

Finally, even if a project is not shared, it is still included in the metrics for total number of projects that are computed at each site,

**Comment by LucaCinquini** [comment]
This can be tested by federating with CoG-CU-DEV and looking at project ABC123, or creating a new project to tweak its shared setting.

**Comment by murphysj** [comment]
Luca and I tested this together using my local system. We had to remove pcmdi9 from my list of nodes and I cannot sync the normal projects at cu dev because I already have stub projects from cu main. I was able to see the test project though by turning on sharing.
