### ISSUE TITLE
Update current site name, domain from cog_settings.cfg

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1215]
Who: Luca
Currently, when a CoG is first installed, the site name to set to:
self._safeSet('SITE_NAME', hostName.upper())
and stored in cog_settings.cfg.

If the administrator ever changes the value to something like ESGF@... (which he/she should), the new value is never read back and stored in the database, with the consequence that the wrong name is propagated to the other CoGs. This needs to be fixed.

**Comment by LucaCinquini** [comment]
Now every time CoG is restarted, the new value of SITE_NAME from cog_settings.cfg is read and stored in the database.

**Comment by LucaCinquini** [comment]
Administrators can apply an easy workaround until the next release: simply use the django admin interface:

https://$HOSTNAME/admin/

select Sites, then your site, and set the display name to the desired value, such as: ESGF@NASA/JPL

The new value will be propagates to all the other CoGs the next time the synchronize with the rest of the federation.

**Comment by murphysj** [comment]
Tested this by...
a) going to cu-dev and changing the node name in the config file
b) reinstalling
c) going to my local sand box
d) reload the peer listing
e) the change appeared locally

closing.
