### ISSUE TITLE
Provide custom view for listing of tech notes

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1217]
Who: Duane Waliser

Duane and the obs4MIPs group would like to provide an automatic listing of all the tech notes associated with obs4MIPs datasets.

**Comment by LucaCinquini** [comment]
I have implemented a general capability to render search results through a custom template. For example, the following URL:

http://localhost:8000/search/cog/?template=obs4mips

will retrieve the search results as usual, but then invoke the template cog/search/obs4mips.html at the time of rendering. As usual, the template can be located inside the CoG distribution, or in the node-specific mytemplates/ directory.

**Comment by LucaCinquini** [comment]
Sylvia can you please check the obs4mips.html table for 508 compliance.

**Comment by murphysj** [comment]
what are we calling this template in both the code and for the user? Is it
somethink like "solr metadata table"?

On Thu, Mar 3, 2016 at 10:25 AM, Luca Cinquini <notifications@github.com>
wrote:

> I have implemented a general capability to render search results through a
> custom template. For example, the following URL:
>
> http://localhost:8000/search/cog/?template=obs4mips
>
> will retrieve the search results as usual, but then invoke the template
> cog/search/obs4mips.html at the time of rendering. As usual, the template
> can be located inside the CoG distribution, or in the node-specific
> mytemplates/ directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1217#issuecomment-191872014>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
"Custom View for Search Results" ?

Attaching a screenshot.
[obs4mips_table.pdf](https://github.com/EarthSystemCoG/COG/files/157311/obs4mips_table.pdf)

**Comment by murphysj** [comment]
To the user, it is not a search because they are not on the search page nor
using the facets.

It is a custom view...

How will project admins know how to modify this w/o making a total mess?
e.g. what info they can harvest?

On Thu, Mar 3, 2016 at 10:32 AM, Luca Cinquini <notifications@github.com>
wrote:

> "Custom View for Search Results" ?
>
> Attaching a screenshot.
> obs4mips_table.pdf
> <https://github.com/EarthSystemCoG/COG/files/157311/obs4mips_table.pdf>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1217#issuecomment-191875702>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
@LucaCinquini 

Ok, made 508 compliant. 
Change title and added explanatory sentence. See what you think.

![obs4mips](https://cloud.githubusercontent.com/assets/1512704/13578954/1b491508-e458-11e5-943e-acf0589bad30.png)

**Comment by LucaCinquini** [comment]
Thanks for updating the table. I changed the title, then it will be up to the obs4mips people to change again as they see fit.
Is it possible to re-instate the alternate white/gray for the rows, I kind of likes it ?

**Comment by murphysj** [comment]
I did not touch the colors. I don't recall ever seeing the alternating
colors.

On Thu, Mar 10, 2016 at 4:55 PM, Luca Cinquini <notifications@github.com>
wrote:

> Thanks for updating the table. I changed the title, then it will be up to
> the obs4mips people to change again as they see fit.
> Is it possible to re-instate the alternate white/gray for the rows, I kind
> of likes it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1217#issuecomment-195107440>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
URL at CU dev is
https://cog-cu-dev.colorado.edu/search/cog/?template=obs4mips

**Comment by murphysj** [comment]
we found that django was automatically adding a trailing slash to url, which caused a ysd. Also, the url was cached, so no one could access the normal search after accessing the template.

Luca fixed this.

**Comment by murphysj** [comment]
verified on cu-dev. closing.
