### ISSUE TITLE
Do not display Solr record version in CoG search interface

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1218]
Who: Atef, Katharina

Atef noticed that we display two different versions in CoG.

E.g. in "Show Metadata":
ID = cmip5.output1.MPI-M.MPI-ESM-LR.historical.day.atmos.day.r1i1p1.v20111006|esgf1.dkrz.de 
Version = 20111006
Timestamp = 2016-01-11T11:20:10.492Z
Version = 1523068395052859392

I think the second version is the __version__ field from Solr used only internally for Solr Cloud and the update process. Maybe it's worth to hide this version so users don't get confused.

**Comment by LucaCinquini** [comment]
Now implemented: Solr version is not displayed neither for dataset metadata, nor for file metadata.

**Comment by murphysj** [comment]
verified on cu dev that second version is no longer present. closing.
