### ISSUE TITLE
Allow search interface to override project fixed constraints

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1219]
Who: Guillaume

We observed a mis-understood behavior regarding the search interface. On https://esgf-node.ipsl.upmc.fr/search/cmip5-ipsl/, the Data Search constraint is set as « project=CMIP5,TAMIP,EUCLIPSE,LUCID,GeoMIP,PMIP3 » as defined in our Google Docs. It appears that the search result is independent of the selected project. In fact, whatever the selected project, « CMIP5 » is automatically re-selected and the project options appears/disappears following the other facets choices. Consequently, if I understand right the constraints seems to enforce a « OR » logical operators among projects options. And the user cannot select « TAMIP » option in order to search TAMIP data only, the discovery will cover all the project options.

But, in this case, we aim to search data among those pre-fixed projects independently.

**Comment by LucaCinquini** [comment]
This should now be implemented: any constraint set by the user in the search interface will override the project fixed constraints.

**Comment by LucaCinquini** [comment]
Additionally, a new behavior has been implemented: if a user visits a URL with a pre-seeded constraint, such as: ?source_id=AIRS, the search will execute the correct search, store the results/constraints in the session, and redirect to the bare URL with no constraints. This is exactly the same behavior as if a user started from the bare URL and selected source_id=AIRS.

**Comment by murphysj** [comment]
@LucaCinquini 

I am not sure I understand what the issue was and therefore how to test....
