### ISSUE TITLE
Enable Globus downloads of "local shard" data

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1220]
Who: Luca

Currently, if data are published to the Local Shard (8982) with GridFTP endpoints, Globus downloads fail because CoG is not able to correctly locate the files that compose that dataset.

**Comment by LucaCinquini** [comment]
Issue solved: now CoG will properly append the "shard=..." parameter to the download request, which will cause the search for files to have the additional parameter: "shards=localhost%3A8982%2Fsolr", which will locate files for that dataset in the local shard,

**Comment by murphysj** [comment]
@LucaCinquini 
not sure I can test this?

**Comment by LucaCinquini** [comment]
You can probably test this after I deploy this version on cu-dev.

**Comment by murphysj** [comment]
I already deployed devel to cu-dev. How do I test it? I have never published anything...

**Comment by LucaCinquini** [comment]
I need to publish some data to the local shard at JPL… not done yet.
thanks, L
