### ISSUE TITLE
Add ESGF group membership to User's Profile page

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1222]
WHO: nicolas.carenton@ipsl.jussieu.fr

Hello,

Is it possible to configure ESGF's CoG so the user's profile page lists
the ESGF projects he has already enrolled in via the ESGF registration
service? (CMIP5_Research, Cordex_Research, ...)

Thanks

**Comment by LucaCinquini** [comment]
Now implemented - projects and groups for a user are retrieved from all federated CoG sites.
I also included the display of roles, both for projects and for ESGF groups.

**Comment by murphysj** [comment]
Luca sent me a screen shot from JPL. We may need to tweak the cosmetics later. I can't test locally.
