### ISSUE TITLE
Increase the number of characters in a Resource description

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1223]
WHO: Sylvia

Ran out of characters on an ESMPy presentation. Find the number and increase it.

**Comment by murphysj** [comment]
Easily done in the Bookmark model.

**Comment by murphysj** [comment]
We backed this out for the moment in order to get 3.3.1 out the door quickly.

**Comment by LucaCinquini** [comment]
The size has been increased to 1000 characters.
If running CoG standalone, you must run the following command after pulling, and before starting CoG:

python manage.py migrate

**Comment by murphysj** [comment]
verified on cu dev. closing.
