### ISSUE TITLE
Deal with cog_info in a federated world

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1224]
WHO: Sylvia

When someone creates an account, they can opt into cog_info. Node admins get an email saying this. 

This only makes sense at CU and NOAA since other nodes may have their own mailing lists.

Figure out what to do....

**Comment by murphysj** [comment]
@LucaCinquini 

One option would be to change the text to read something like "subscribe to node notificaitons".

Question is, do other nodes have or intend to have a mailing list for all their users?

**Comment by murphysj** [comment]
on the 2/9/15 call Cecelia requested we subscribe all node users around the globe to cog info

we need to investigate if there is a way to do that automatically.

**Comment by murphysj** [comment]
Google groups are not really an option for this:
https://support.google.com/groups/answer/46438?hl=en

Anyone who is a member of the group can login and do things. Not what we want. Plus there are some things that require google accounts.

**Comment by murphysj** [comment]
CU has free option:
http://www.colorado.edu/oit/services/messaging-collaboration/bulk-messaging/email-list-manager/help/manage-email-common-commands

Limitations:

- Only 1000 people per list. Way to small
- Auto subscription must come from the user or the owner at CU. Will need to see if it can come from the software

**Comment by murphysj** [comment]
We can have cog send an email subscription request as follows:

To: cog_info-request@list.noaa.gov
Subject: subscribe address=user.email_address

This does require a confirmation on their part.

While mailman does have a no confirmation option, it must be enabled by the node admin and I don't know if it can be done on a list by list basis.

**Comment by LucaCinquini** [comment]
This looks like a good option to me.
thanks, L

**Comment by LucaCinquini** [comment]
I have implemented the changes and tested on the JPL dev server, where you can create an account and send email. You son't be able to test this on cu-dev since it will redirect creation of accounts to hydra. You might be able to test on your local laptop if you enable a mail server, otherwise just close the tickets and test in production :)...

**Comment by murphysj** [comment]
will have to test in production!
