### ISSUE TITLE
Tweak Configure Peers template

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1226]
WHO: Sylvia

The template says "must save first" but there is no save button. It is really "submit first"

Redo the page so that is clear.

**Comment by murphysj** [comment]
@LucaCinquini 
I redesigned this page based on my understanding of the workflow. Is the below changes correct? Aesthetically pleasing?
![peer_node_config](https://cloud.githubusercontent.com/assets/1512704/12856307/829141d2-cc01-11e5-924d-86dadd69d202.png)

**Comment by LucaCinquini** [comment]
Hi Sylvia,
	thanks, it looks good. I would just insert a little more space between the yellow message and the steps below,
but overall it makes the workflow clearer.

thanks, Luca

**Comment by murphysj** [comment]
@LucaCinquini 
How does this look, I put a little space at the top too...

![peer_node_config](https://cloud.githubusercontent.com/assets/1512704/12895065/e990c058-ce57-11e5-9209-a496066a7f51.png)

**Comment by LucaCinquini** [comment]
Nice, thanks.
L

**Comment by murphysj** [comment]
verified on cu-dev. closing.
