### ISSUE TITLE
Problem with /login2/ when using external IdP

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1231]
Who: Matthias Buchner

Matthias is using an ESGF configuration that uses a local CoG connected to the DKRZ external IdP. He is reporting that when he tries to login with the /login2/ or /admin/ URLs, he is always red-directed to the change password page at DKRZ: 

https://esgf-data.dkrz.de/login/?next=/password/update/1/

**Comment by LucaCinquini** [comment]
I think this is a consequence of the fact that his local "rootAdmin" account is different than the DKRZ "rootAdmin" account. The PasswordMiddleware executes this check for each HTTP request:

if request.user.is_authenticated() and request.user.profile.type==1 and request.user.profile.hasPasswordExpired():
--> redirect to change_password at IdP

which will happen if for some reason: self.last_password_update = None

The easiest solution is to disable the PasswordMiddleware since there has been no more talk of making the password expire. If we want this functionality back, we will make it work with local accounts as well.

**Comment by murphysj** [comment]
@LucaCinquini 
FYI...I do see having to make our passwords expire necessary at some point. It is just a better security protocol.

**Comment by LucaCinquini** [comment]
For now the PasswordMiddleware has been disabled.
