### ISSUE TITLE
Pagination on All Users only does not work with search

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1241]
WHO: Sylvia

When you type a search into the box you get subselected results. When you try to page, it reverts to all.

**Comment by LucaCinquini** [comment]
This is now fixed. The solution should work for listing all node users, list users enrolled in a group, and list users that are pending approval.

**Comment by murphysj** [comment]
@LucaCinquini 
I just tried testing this on the CSS branch on cu-dev. It did not work. 

Here is what I did. 

1) Go to the "list all system users page"
2) Type .edu in the search box. (this brings up 154 results)
3) Click on page 2 of the pagation. The page shifts but reverts back to the full user listing not those with only a match of .edu

**Comment by murphysj** [comment]
Luca had done the membership templates, not the admin templates. 

It works now...tested on cu dev
