### ISSUE TITLE
Don't show Federated Nodes widget if empty

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1242]
WHO: Sylvia

Went to the swedish node. they have the nodes widget turned on but it is empty and looks bad.

**Comment by murphysj** [comment]
added if statement.

**Comment by murphysj** [comment]
verified on cu dev. 

@LucaCinquini does the text work for you?

![federated](https://cloud.githubusercontent.com/assets/1512704/13269758/c1434bf2-da46-11e5-8fc4-d5c928f3c21b.png)

**Comment by LucaCinquini** [comment]
Sure.
L

**Comment by murphysj** [comment]
Saw on in my local sandbox that this was not working. Investigate.

**Comment by murphysj** [comment]
Turns out that my new installation installed an extra row in the site table. This was empty. We removed it via the django interface and noted it in the developers guide.
