### ISSUE TITLE
Prevent non-ascii characters in usernames, openids

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1245]
Who: Katharina

I just had an issue with an user who had an umlaut (ü) in his last name. After creating the account he got an Server Error. However, the account was created in cogdb but not in esgcet so re-registering was not possible.

I'm not sure whether we can support umlauts in ESGF but we should at least check this in CoG before sending the information to the DB.

**Comment by LucaCinquini** [comment]
"On a Mac:
Use the OPTION key. Hold down OPTION and push ‘s’ to get ß. For the umlauted characters, hold down OPTION and push ‘u’. Release OPTION, then type the desired base letter (a, o, u, A, O, or U). The umlaut will appear over the letter you typed. (So to type ü, you should hold down OPTION, press u, then release OPTION and press u again.)"

**Comment by LucaCinquini** [comment]
Now all fields (except for the password) are checked - they must NOT contain any non-ascii characters. This is in addition to other previous value requirements.

**Comment by murphysj** [comment]
I tests first_name, last_name, user_name, and email for non-ascii characters. They all caught them and threw the appropriate error.
