### ISSUE TITLE
Limit the list of available facets in the project search configuration

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1246]
Who: Luca

Right now, when a project administrator wants to add a search facet to the project, the admin interface returns a list that includes ALL facets in the ESGF federation, which can be confusing and lead to empty facets. We need to limit this list to only those facets that are populated for that project data.

**Comment by LucaCinquini** [comment]
Implemented.

**Comment by murphysj** [comment]
switch project from obs4mips to cmip5. facets change, so they seem project specific.
