### ISSUE TITLE
Remove dependency on /esg/config/facets.propreties

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1247]
Who: Luca

Right now, new search facets still need to be configured in /esg/config/facets.properties, which adds an un-necessary dependency to the CoG search configuration. We need to modify the ESGF search services to retrieve the list of allowed facets dynamically.

**Comment by murphysj** [comment]
Moving to 3.5

**Comment by LucaCinquini** [comment]
Actually I simply modified the esgf-search module to NOT check that a facet is allowed. Unrecognized facet name/value pairs such as ?x=y will simply cause the search to retrieve no results, as it happens in Solr.

**Comment by LucaCinquini** [comment]
This was done by changing the esg-search code to query the list of available facets from all configured shards, when the server is first started, or every 24 hours. The file facets.properties is no longer needed.
