### ISSUE TITLE
'.' in usernames/openids don't work

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1248]
Who: Luca

People have reported that usernames with '.' in them do not work ? Must verify and possibly exclude that character.

**Comment by LucaCinquini** [comment]
This is not an issue: I was able to create an account with username='luca.cinquini@jpl.nasa.gov' and openid=https://esgf-node.jpl.nasa.gov/esgf-idp/openid/luca.cinquini@jpl.nasa.gov and login both with the full openid, and with the IdP selector.

**Comment by murphysj** [comment]
I was able to create a username sylvia.murphy and login using login2 in my local sandbox. This might be an issue with foreign keyboards but for now I can not reproduce.
