### ISSUE TITLE
Revisit the "All Node Users" table

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1249]
Who: Luca

Sylvia noticed that the "All Node Users" table now shows at the top a lot of users who have no first name, last name, or openid. Must investigate.

**Comment by LucaCinquini** [comment]
I tracked this down to the fact that when a remote user logs into this site using the IdP selector, the user attributes are NOT transmitted. If instead the user types in the full openid, the attributes are propagated correctly. ESGF is not likely to drop support for the IdP selector, so we need to adapt. I think that the "All Node Users" table should be modified to show the user home node, and at least in the case of remote users, their openid instead of their last/first name and email. We should discuss this.

**Comment by murphysj** [comment]
@LucaCinquini 

I have shorted the date columns

I put in a if statement... if a last_name exists it displays that info. If not it displays the openid.

I can't test this b/c I don't have any openid's on my system nor does cu dev

One issue we may have is that the user_profile.openids is plural...there may be more than one.

Is there anyway for you to look at this?

**Comment by LucaCinquini** [comment]
Perhaps.. if you check in the code I can try
There’s also a method to get the first openid: user_profile.openid() I believe.
L

**Comment by murphysj** [comment]
never mind. I was accidentally logging into noaa.

On Thu, Mar 3, 2016 at 12:02 PM, Luca Cinquini <notifications@github.com>
wrote:

> Perhaps.. if you check in the code I can try
> There’s also a method to get the first openid: user_profile.openid() I
> believe.
> L
>
> On Mar 3, 2016, at 11:59 AM, Sylvia Murphy <notifications@github.com>
> wrote:
>
> > @LucaCinquini
> >
> > I have shorted the date columns
> >
> > I put in a if statement... if a last_name exists it displays that info.
> If not it displays the openid.
> >
> > I can't test this b/c I don't have any openid's on my system nor does cu
> dev
> >
> > One issue we may have is that the user_profile.openids is plural...there
> may be more than one.
> >
> > Is there anyway for you to look at this?
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/1249#issuecomment-191915735>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
@LucaCinquini 

since we get these funky looking accounts when the CU node says...this openID is not federated and since that results in a home node of CU, I am not sure the home node column does a whole lot of good because the home node is listed as CU for these foreign openids.

What do you think?

**Comment by murphysj** [comment]
@LucaCinquini 
here is what it currently looks like:
![node_users](https://cloud.githubusercontent.com/assets/1512704/13511168/4c3f170c-e151-11e5-8978-33851bfe9e9b.png)

**Comment by LucaCinquini** [comment]
I would leave the column for now, and possibly take it away later. I personally like to know where these users have their home page.
thanks, L

**Comment by murphysj** [comment]
luca suggests moving username to first column and ordering on that vice last_name.

**Comment by murphysj** [comment]
done. verified on cu dev
