### ISSUE TITLE
Deal with Django context_?? deprecation warnings

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1253]
WHO: Sylvia

WARNING: File /esg/config/esgf_cogs.xml does not exist, skipping update of ESGF peer nodes
/Users/sylvia.murphy/COG/venv/lib/python2.7/site-packages/Django-1.9.1-py2.7.egg/django/shortcuts.py:45: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
  using=using)

WARNING:py.warnings:/Users/sylvia.murphy/COG/venv/lib/python2.7/site-packages/Django-1.9.1-py2.7.egg/django/shortcuts.py:45: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
  using=using)

/Users/sylvia.murphy/anaconda/lib/python2.7/importlib/__init__.py:37: RemovedInDjango110Warning: django.core.context_processors is deprecated in favor of django.template.context_processors.
  __import__(name)

WARNING:py.warnings:/Users/sylvia.murphy/anaconda/lib/python2.7/importlib/__init__.py:37: RemovedInDjango110Warning: django.core.context_processors is deprecated in favor of django.template.context_processors.
  __import__(name)

/Users/sylvia.murphy/COG/venv/lib/python2.7/site-packages/Django-1.9.1-py2.7.egg/django/template/defaultfilters.py:509: RemovedInDjango110Warning: django.utils.html.remove_tags() and the removetags template filter are deprecated. Consider using the bleach library instead.
  return remove_tags(value, tags)

WARNING:py.warnings:/Users/sylvia.murphy/COG/venv/lib/python2.7/site-packages/Django-1.9.1-py2.7.egg/django/template/defaultfilters.py:509: RemovedInDjango110Warning: django.utils.html.remove_tags() and the removetags template filter are deprecated. Consider using the bleach library instead.
  return remove_tags(value, tags)

**Comment by LucaCinquini** [comment]
The old "TEMPLATE*" settings in settings.py have been removed in favor of the new Django TEMPLATES setting.

**Comment by LucaCinquini** [comment]
The "removetags" built-in filter has been removed in favor of using the bleach library to sanitize the page title.

**Comment by LucaCinquini** [comment]
I think the last warning "django.core.context_processors is deprecated in favor of django.template.context_processors." is internal to the django file "shortcuts.py" and should be taken care in one of the upcoming django releases. If instead you notice a specific page where that happens, please let me know.

**Comment by murphysj** [comment]
Did you merge devel to css, I am still getting this warning:
/Users/sylvia.murphy/COG/venv/lib/python2.7/site-packages/Django-1.9.4-py2.7.egg/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

WARNING:py.warnings:/Users/sylvia.murphy/COG/venv/lib/python2.7/site-packages/Django-1.9.4-py2.7.egg/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

**Comment by murphysj** [comment]
verified locally, which is the only place I can see the warnings.
