### ISSUE TITLE
Enable setting to disregard captcha errors

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1265]
Who: Nicolas

Nicolas is working on a test to automatically create a user account in CoG. For this to work, he needs the captcha to be disabled when testing.

**Comment by LucaCinquini** [comment]
Now there is an additional configuration parameter:
USE_CAPTCHA = True/False
that can be used by the test suite to enable/disable the captcha when creating a user account. Every time the value is changed, CoG needs to be restarted for the new setting to be read. The default value is True.

**Comment by murphysj** [comment]
Verified locally by turning captcha on and off.
