### ISSUE TITLE
Avoid using " character when creating user passwords

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1267]
Who: Katharina

Hi all,
We have some issues for passwords containing 'special' special characters:
1. A '"' in your password does not work for wget's '-H'. The wget call passes the password in quotes so the end of the password can not be detected.
2. A '/' in your password does not work for myproxy-logon. I have no idea why.
Can we fix this or shouldn't we allow the use of '/' and '"' in passwords?
Thanks,
Katharina

**Comment by LucaCinquini** [comment]
Hi Luca,
Avoiding the '"' sounds like a good idea. Since the '/' issue seems to appear only for one particular machine I think this one could be allowed.
Thanks,
Katharina

**Comment by LucaCinquini** [comment]
Implemented.

**Comment by murphysj** [comment]
verified locally.
