### ISSUE TITLE
Improvements to obs4mips table

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1273]
Who: Robert

 Lower on the list of improvements … some format changes to your autogenerated page.
o Expand column size for Instrument so that all dataset “instrument” values only occupy 1 line
o Expand Tech Note column size so that “tech note” is on a single line.

**Comment by murphysj** [comment]
done. emailed robert to see if he like it. 
![after](https://cloud.githubusercontent.com/assets/1512704/14824861/b8616f3a-0b94-11e6-9641-d1a016d0ea35.png)

**Comment by murphysj** [comment]
Yes, this is better.
The main thing is to have the widths of the first and last columns large enough so that entries in those columns do not force a second line.  Its ok for the fields in the middle 2 columns to force a second line occasionally.
Thanks,
Robert

**Comment by murphysj** [comment]
URL at CU dev is
https://cog-cu-dev.colorado.edu/search/cog/?template=obs4mips

**Comment by murphysj** [comment]
luca moved to production. can see it there. closing.
