### ISSUE TITLE
Enable searching on date less than a given value

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1283]
Who: Martina

As part of enabling display of citations, CoG need to be able to allow users to search on datasets with a date less than a certain value.

**Comment by LucaCinquini** [comment]
Now implemented, with call to the underlying ESGF search service. Both min_version and max_version are supported. The panel is toggled through the "[More Search Options]" link. The search will only work if the target ESGF search service has been updated too.

**Comment by murphysj** [comment]
I checked the new search options link. since ESGF is updated, I can't tell if the dates work, but the template is fine.
