### ISSUE TITLE
Fix inconsistency in node names

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1287]
Who: Luca

Currently, the name of a remote CoG node is set from two different sources:

a) Every time the local CoG is restarted, those names are read from the file esgf_cogs.xml

b) Every time the local CoG synchronized with the remote CoGs, the node names are over-ridden with the values imported from the remote configuration

This can lead to inconsistency if the remote administrator has not inserted the correct name in their cog_settings.cfg file.

**Comment by LucaCinquini** [comment]
From now on, the the esgf-cogs.xml will be the only source of information about the remote node names. The name of a remote node will NOT be changed when synchronizing that remote node with the local node.

**Comment by murphysj** [comment]
verified on cu dev
