### ISSUE TITLE
Can't save user

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1288]
Hi Luca,

Try clicking on this link: https://www.earthsystemcog.org/user/update/581/

then hitting submit. I am getting a 500 server error.

**Comment by murphysj** [comment]
This seems difficult to fix right now. I think it’s related to the user having one or more URLs, which we have disabled in the page…. 
You can file a bug report for the next release. What do you want to do with this user, remove him ?
thanks, L

**Comment by LucaCinquini** [comment]
I think I fixed the issue: now, the first thing that happens when a User object is updated, is that any (obsolete) attached UserUrl is deleted. I was able to run the Update command on this user on my test machine. To update the live instance we will need to wait until this next release is deployed.
