### ISSUE TITLE
URI too long for wget.sh generation from data cart

### ISSUE THREAD

**Issue by cofinoa** [EarthSystemCoG/COG#1289]
When users wants to generate a wget.sh for a large collection of datasets the request URI for the esgf-search is too long.

**Comment by cofinoa** [comment]
The request must be done using a POST request instead a GET.

**Comment by LucaCinquini** [comment]
CoG has been switched to using POST when issuing a request to esg-search to create a wget scripts. But for this to work, the esg-search service needs to have been updated to reflect this issue:
https://github.com/ESGF/esg-search/issues/97

So, for now, we will keep the CoG code in place but still issue GET requests, until ALL ESGF nodes have been updated to use the esg-search release 4.9.1 or later.

**Comment by LucaCinquini** [comment]
When the time comes, the code to be uncommented is contained in file _wget_js.html

**Comment by LucaCinquini** [comment]
Moving to CoG release 3.9 to allow for all ESGF nodes to update their esg-search first.

**Comment by LucaCinquini** [comment]
Now switching CoG to issue POST requests.
