### ISSUE TITLE
Cannot change user password with django admin form 

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1291]
Who: Sylvia

Ryan needed a password update, he was not getting the password emails. 

a) cog form throws an error saying the admin password is not correct. I logged in with the admin password, so I know that is correct. (turns out the label was not really correct. It calls for the administrator's password, which really means the password of the person using the form, not the admin password. I added help text to the form to make that more clear.)

b) tried changing the password via the django admin interface. I can change it but can't login with that password. If this form does not work, perhaps we should remove it.

**Comment by LucaCinquini** [comment]
Does changing the password with the CoG interface work ? If so, we are good. We should NOT allow people to change the password with the django admin interface, because it will not change the password in the ESGF database. We also cannot remove that form because it's part of the native django package.

**Comment by murphysj** [comment]
Changing it via the cog interface did work, once I figured out the correct pword. If we can't get rid of the django form, can we add a comment or something in there to say...don't use this cuz it won't change anything in the ESGF DB?

How customizable is the django interface?

**Comment by murphysj** [comment]
I changed the password help text in the django admin interface. The previous help text pointed to a change form. Now that is gone and it says:
"Password changes via the admin interface have been disabled since they will not be saved to the ESGF database."

**Comment by murphysj** [comment]
verified on cu dev
