### ISSUE TITLE
Remove example PHP code

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1297]
Who: Rachana

ANL security team has identified PHP files in the YUI distribution that comes with CoG. The code is never executed (since the Apache server does NOT contain a PHP module), only rendered as text, but it is good to remove such code to avoid triggering false security vulnerabilities.

**Comment by LucaCinquini** [comment]
The directory affected under $COG_INSTALL_DIR are:

[cinquini@esgf-node cog_install]$ sudo rm -rf ./cog/static/js/yui-2.9.0/examples
[cinquini@esgf-node cog_install]$ sudo rm -rf ./cog/static/js/yui/examples
[cinquini@esgf-node cog_install]$ sudo rm -rf ./static/js/yui-2.9.0/examples
[cinquini@esgf-node cog_install]$ sudo rm -rf ./static/js/yui/examples
[cinquini@esgf-node cog_install]$ sudo rm -rf ./build/lib/cog/static/js/yui/examples
[cinquini@esgf-node cog_install]$ sudo rm -rf ./build/lib/cog/static/js/yui-2.9.0/examples

**Comment by LucaCinquini** [comment]
The "examples" directory from YUI and Grappelli have been removed from the CoG source code.

**Comment by murphysj** [comment]
verified locally when I installed.
