### ISSUE TITLE
Add text about data on project join message

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#1302]
WHO: Luckas

**Comment by murphysj** [comment]
@lukaszlacinski @LucaCinquini 

I added one line of text to this message. I doubt anyone will actually read this but here it is. Let me know what you think. 

We may run into issues if there ARE projects that require project membership to download data. 

![project_message](https://cloud.githubusercontent.com/assets/1512704/17144641/ac48b236-5314-11e6-9942-58457259e608.png)

**Comment by lukaszlacinski** [comment]
It may be helpful if this text can be customized per project. A custom project template would be loaded if it exists, otherwise the general membership request template would be loaded.

**Comment by murphysj** [comment]
That would be, but a much larger task since it would involve a database adjustment.

@LucaCinquini if we were to do this, it seems like a new text field in the update project page would be where this lives. We could ticket that for some point in the future.

**Comment by LucaCinquini** [comment]
We might be able to do this by simply loading a template snippet, no database change ? I’ll have to look into it…

**Comment by murphysj** [comment]
verified on cu dev. 
![project_text](https://cloud.githubusercontent.com/assets/1512704/18143775/b75b1d16-6f80-11e6-83f8-3de51c4db881.png)

**Comment by murphysj** [comment]
we postponed custom messages to a later date.
