### ISSUE TITLE
Return HTTP status code 404 for non-existing URLs

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1309]
Who: Luca

The JPL scan identifies a Low security risk when pages that do not exist, such as:

https://esgf-node.jpl.nasa.gov/ac/subscribe/admin.aspx/

return a 200 status code. We should instead return 404 (not found).

**Comment by LucaCinquini** [comment]
The following classes of URLs will now immediately return http status 404 (not found)

**Comment by LucaCinquini** [comment]
Additionally, I have made the URL patterns case-insensitive, so that a request to *.php or *.PHP will equally fail.

**Comment by murphysj** [comment]
@LucaCinquini 

when I go here: https://cog-cu-dev.colorado.edu/ac/subscribe/admin.aspx/
I just get a blank white page?

**Comment by LucaCinquini** [comment]
That’s ok, the HTTP status code should be not found or something like that, you can look at that with FireFox.

**Comment by murphysj** [comment]
looked at response header, 404 was found.
