### ISSUE TITLE
Removing references to yui.yahooapis.com

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1315]
Who: NOAA security scan

"Additionally, linking to external, non-approved third party content delivery networks is not recommended"

see: https://esgfdev/user/add/

**Comment by LucaCinquini** [comment]
In file: cog/templates/cog/account/user_form.html
the YUI content used to be loaded from: "http://yui.yahooapis.com/2.9.0"
now it's loaded from the local copy of the library at: {{ STATIC_URL }}js/yui-2.9.0

**Comment by murphysj** [comment]
I see the code change.
