### ISSUE TITLE
Do not display user openid, username inline

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1316]
Who: NOAA security

The "Forget Openid" functionality allows a user to retrieve their openid, username if they provide their email. Currently, this functionality both emails the information to the user, but also displays it online. The online display could be used to guess user credentials and execute a brute-force attack.

**Comment by LucaCinquini** [comment]
The online display of information has been removed - the information is just sent by email now.

**Comment by murphysj** [comment]
Can't see this in action because we need an IDP but I see in the code the extra text has been removed.
