### ISSUE TITLE
Prevent dangerous tags in wiki pages

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1317]
Who: NOAA security scan

CoG wiki pages are currently allowed (through CKEditor) to embed tags such as <iframe>, <form> and <script>, which can be used maliciously.

**Comment by LucaCinquini** [comment]
Not any more - the wiki update is now rejected if any of these tags is found.

**Comment by murphysj** [comment]
I added a period to the warning plus the following sentence:

"Use the source button to remove."

Sometime, these tags get added when a user copies and pastes content and they may not have done purpose.

**Comment by murphysj** [comment]
verified on cu dev.
