### ISSUE TITLE
Do now show 'admin' role for CoG Project Memberships

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1318]
Who: NOAA security scan

Currently, the user profile page shows the user roles for each project, such as 'admin' role. This information is sensitive and can be used to obtain privileged accounts.

**Comment by LucaCinquini** [comment]
Now the CoG project roles are displayed only if the user logged in is the same as the user profile, or the user logged in is a project or site administrator.

**Comment by murphysj** [comment]
Can't see this action without an IDP but I see the code change.
