### ISSUE TITLE
Validate content of uploaded files

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1319]
Who: NOAA security scan

Currently, when a file is uploaded through the CoG interface, not much validation is performed on the actual content of the file.

**Comment by LucaCinquini** [comment]
Now we are using python-magic to inspect the file content for its mime type. The file extension must be one of the approved types (the file MUST have an extension), and its mime type must be approved for that specific extension.

**Comment by LucaCinquini** [comment]
The idea is to prevent files from being executed on the server... If the image itself is bad, we can always track down who uploaded it. I don't think we can inspect the image per-se...

**Comment by murphysj** [comment]
This code writes the file to a temporary location. Is there any risk in that if the goal is to prevent the file from being run on the server?

**Comment by murphysj** [comment]
tested a file w/o an extension
a pdf file with a ppt extension
and a
file with a .garb extension

all produced an error.
