### ISSUE TITLE
Replace use of predictable random generator

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1325]
Who: NOAA security scan

The CoG plugin for downloading files through Globus uses the function "randint()" to create the path of a temporary file. This has been flagged as insecure because:

"Standard pseudo-random number generators cannot withstand cryptographic attacks."

Must replace with a cryptographically-secure algorithm.

**Comment by LucaCinquini** [comment]
Done, now using "SystemRandom().randint()".

**Comment by murphysj** [comment]
This code must be outside of the cog source code. My search did not find it...?

**Comment by murphysj** [comment]
actually the code is: cryptogen = SystemRandom()
found it.
