### ISSUE TITLE
Change 'PASSWORD' string

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1327]
Who: NOAA security scan

The security scan flags the use of the string 'PASSWORD' (case sensitive) as insecure, although the reviewer has marked it as "not an issue".

**Comment by LucaCinquini** [comment]
Nevertheless, I changed to the string 'PWD' everywhere in the code to avoid being flagged by future scans.

**Comment by murphysj** [comment]
I still see this string in lots of places. Particularly in the install.py and forms_account.py.

**Comment by murphysj** [comment]
It is only upper case that matters.
