### ISSUE TITLE
Third party filebrowser subject to path manipulation

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1330]
Who: NOAA security scan

The third-party filebrowser software that is used in CoG is susceptible to file path manipulation attackes in its open() and save() methods.

**Comment by LucaCinquini** [comment]
Those methods have been wrapped in a "validate_path()" method that checks for the presence of the infamous "." character.

**Comment by murphysj** [comment]
verified by code review.
