### ISSUE TITLE
Loading gif animation from yahoo causes ssl warning (mixed content)

### ISSUE THREAD

**Issue by pchengi** [EarthSystemCoG/COG#1382]
The file yui_panels.html refers to a rel_interstitial_loading.gif which is an animation of a 'loading progress bar'. This file is unfortunately not available through https, so it triggers a mixed content warning on ESGF sites.  Replace this file with one which is available over https, or host this file elsewhere where it can be accessed over https.

**Comment by LucaCinquini** [comment]
Fixed by loading the same gif from local content.
