### ISSUE TITLE
filter files by variable

### ISSUE THREAD

**Issue by alaniwi** [EarthSystemCoG/COG#1403]
For CMIP5 and related projects, where multiple variables are combined into a single dataset, it would be good to provide a way to filter files by variable if the user has specified one of the related criteria ("variable" or "variable long name" or "CF standard name") in the search UI.  Currently these will be used to filter the experiments, but then the files within an experiment are unfiltered.  But these fields are available in the file metadata as well as the dataset metadata, so could be used for filtering.

**Comment by sashakames** [comment]
This functionality, while not great, exists with the "More Search Options" link to toggle the view
