### ISSUE TITLE
Replace globusonline integration with globus SDK

### ISSUE THREAD

**Issue by sashakames** [EarthSystemCoG/COG#1405]
The globusonline module to initiate a transfer is now deprecated.  We need to replace it with the current SDK.

**Comment by mauzey1** [comment]
@sashakames Replacement of the old transfer API with the new one is part of my current effort to update CoG to Django 2.2.

**Comment by mauzey1** [comment]
@sashakames Globus SDK is now being used by CoG so I think we can close this issue.

**Comment by sashakames** [comment]
Was this ever put into production and tested? I can't remember @nathanlcarlson ?

**Comment by mauzey1** [comment]
@sashakames @nathanlcarlson 
The changes for Globus SDK have been pushed to the `devel` branch of CoG.

**Comment by nathanlcarlson** [comment]
I don't believe it was put in production but see #1423  for more info.

**Comment by sashakames** [comment]
Thanks I recall this being tested.  We'll do a globus transfer test when we test the Py3 CoG on fedtest or can consider a production deployment sooner ( a matter of merging...)
