### ISSUE TITLE
zero files shown for remote data node

### ISSUE THREAD

**Issue by sashakames** [EarthSystemCoG/COG#1426]
This appears to be an issue if the indexnode listed in the dataset record is remote, ie. different than the node hosting CoG.  Files don't appear in this case when "Show Files" is clicked in search results.  I recall an attempt to use only the local search API which we didn't get to work.  Perhaps that code was merged in.  Perhaps that merge can be identified and rolled back,

**Comment by mauzey1** [comment]
The commits from https://github.com/EarthSystemCoG/COG/tree/index_node_usage are in the Python3 branch and devel.  This appears to be where the changes to "Show Files" is coming from.  Should we remove those commits from both branches?

**Comment by sashakames** [comment]
Sounds like a reasonable approach, thanks!  If you have a separate branch to test this, let me know, or just make the change on your `python_3` branch.

**Comment by sashakames** [comment]
The file count issue is solved. I noticed a separate issue with wget scripts.  not just remote.  Its broken so will open a separate issue.
