### ISSUE TITLE
Be able to save a data search path and associated results

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#189]
WHO: Christiane

Save the set of ESGF search criteria (used to generate data search results) back to the workspace along with the search results.

**Comment by murphysj** [comment]
Luca,
Was this taken care of with the Restful URL that you created in 2.8? If so we can close this.

**Comment by LucaCinquini** [comment]
Y

On Jan 26, 2015, at 10:58 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Luca,
Was this taken care of with the Restful URL that you created in 2.8? If so we can close this.

**Comment by murphysj** [comment]
This was done in 2.8.
