### ISSUE TITLE
File description is not carried over to resource URL description

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#345]
WHO: Sylvia
Benefits: All users

When you upload a file, you can give it a description.  When you link to the file via a resource URL, you have to create a new description.  If the system was smart enough, it would see that the fiel had a description  and populate the resource accordingly.

**Comment by LucaCinquini** [comment]
This is done as part of ticket #346

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
