### ISSUE TITLE
Enable links to non-wiki pages in the left navigation bar

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#438]
WHO: Jillian
Benefits all users

Allows for links to non-cog items and makes the left nav bar that much more powerful.

**Comment by LucaCinquini** [comment]
Now implemented, will demonstrate at the next call.

**Comment by murphysj** [comment]
I changed the link name in the left nav bar and added some help text on the template

**Comment by murphysj** [comment]
verified on cu dev. closing.
