### ISSUE TITLE
Add captcha (or similiar) to the registration process

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#476]
WHO: Sylvia
Benefits: System Admins who get spam

We are starting to see spam on CoG.  These are bogus project registrations.   Adding captcha would cut down on bogus registrations.

**Comment by murphysj** [comment]
Silverio recently did this with the ESMF registration. We can talk to him about how easy this is to do.

**Comment by LucaCinquini** [comment]
I actually found a real nice package called django-simple-captcha and use it, it makes like much simpler.
It also comes with some configuration settings which were added to settings.py (other parameters are available also but were not used).

The only problem is that for some reason the package does not install cleanly when declared as a dependency of CoG, it must be installed manually via pip as follows:

source venv/bin/activate
(to activate the CoG python virtual environment)
pip install django-simple-captcha==0.4.5

**Comment by murphysj** [comment]
Tested locally. Works great.
Will test on dev-hydra later

**Comment by murphysj** [comment]
verified on dev-hydra.

**Comment by murphysj** [comment]
Format of this is totally different in chrome and FF.  I played with it a while. No luck yet.

Also, we don't want this for profile updates, only on registration.

**Comment by LucaCinquini** [comment]
Ok I have a fixed for showing the captcha only at registration, but I am not sure onto which branch I should add it.
The captcha looks ok to me on Safari and Chrome, the formatting is wrong on FireFox but I am sure you can use your great CSS knowledge to fix it.

**Comment by murphysj** [comment]
What file did you modify?


On Wed, Jul 29, 2015 at 3:17 PM, Luca Cinquini <notifications@github.com>
wrote:

> Ok I have a fixed for showing the captcha only at registration, but I am
> not sure onto which branch I should add it.
> The captcha looks ok to me on Safari and Chrome, the formatting is wrong
> on FireFox but I am sure you can use your great CSS knowledge to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/476#issuecomment-126097950>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
I have made the fixes (user_form.html and forms_account.py) - checked into css branch.

Also I noticed that the password fields have been moved up in the registration form... It seems unconventional and I am not sure I like it :(.... Any chance we can move them back after the username and perhaps other personal information ?

**Comment by murphysj** [comment]
On 8/5/15, Luca and I decided to split these out.

**Comment by murphysj** [comment]
Tested on my local system. captcha no longer shows up on an update and I was able to save. 
closing.
