### ISSUE TITLE
Create place to display a project's tags

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#565]
WHO: Luca
Benefits: All users

Now that we have project tagging we should display them someplace on the page.

**Comment by LucaCinquini** [comment]
I have implemented the display of the current project tags underneath the project browser. It might require style changes.

I still need to do the display of the other project tags as the user hover over the list.

**Comment by murphysj** [comment]
After the 3/3/15 cog tech call, we got away from the widget and just displayed them as a string of text below the PB.

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
