### ISSUE TITLE
Enable search facet grouping via a web interface 

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#635]
WHO: Arpana
Benefits: All users

For QED-2013 Luca created the ability to group search facets.  Since time was short, he did this via a configuration file.  This functionality needs to be extended to that users can do this in a web interface.

**Comment by LucaCinquini** [comment]
Now the admin page for configuring the search facets includes full functionality for creating, updating, deleting and ordering search facet groups, as well as ordering search facets, and assigning them to groups. This functionality parallels the capability of exporting and importing the search facet configuration to local files.

**Comment by LucaCinquini** [comment]
Sylvia could you please:

o Add some style to the search facets table that highlights in light blue each search group, while search facet rows are kept white

o Update the web instructions to configure the search facets for a project

**Comment by murphysj** [comment]
@LucaCinquini 

Groups will show up whether or not there is a facet in there or not. We should only show groups that have facets

**Comment by LucaCinquini** [comment]
Good point, done and re-merged with css. You may redeploy.

**Comment by murphysj** [comment]
verified on cu dev. closing.
