### ISSUE TITLE
Prevent users from registering usernames with non-standard characters.

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#650]
Prevent users from registering usernames with non-standard characters.

**Comment by murphysj** [comment]
Luca, Was this done as part of the OpenID change?

**Comment by LucaCinquini** [comment]
I don’t think so…
L

On Jan 26, 2015, at 11:35 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Luca, Was this done as part of the OpenID change?

**Comment by LucaCinquini** [comment]
Duplicate of COG#1245, closing.
