### ISSUE TITLE
Be able to download data via Globus Online

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#691]
WHO: ESGF 

This is currently not functional in ESGF at all.

**Comment by murphysj** [comment]
@LucaCinquini 

High priority for Robert for 2.12.

**Comment by LucaCinquini** [comment]
End-to-end workflow completed, using shared "JPL" endpoints so the user doesn't have to insert their password again. Documentation for users and administrators to be authored on the CoG site at CU.

**Comment by murphysj** [comment]
@LucaCinquini 

Can I test this w/o access to JPL? You may just want to close this one out.

**Comment by murphysj** [comment]
@LucaCinquini 
Was going to test the workflow and documentation via chrome. JPL is down. Do you plan to have up today or should I move on to other things?

**Comment by LucaCinquini** [comment]
Yes I am rebooting that right now…
L

On May 22, 2015, at 9:25 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucaCinquini<https://github.com/LucaCinquini>
Was going to test the workflow and documentation via chrome. JPL is down. Do you plan to have up today or should I move on to other things?

**Comment by LucaCinquini** [comment]
Hi Sylvia,
 you should be able to check now. Start from:

https://esg-datanode.jpl.nasa.gov/

and do a search on obs4mips, selecting data-node=esg-datanode.jpl.nasa.gov<http://esg-datanode.jpl.nasa.gov>

Then proceed with Globus download…

thanks, Luca

On May 22, 2015, at 9:26 AM, cinquini <luca.cinquini@jpl.nasa.gov<mailto:luca.cinquini@jpl.nasa.gov>> wrote:

Yes I am rebooting that right now…
L

On May 22, 2015, at 9:25 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucaCinquini<https://github.com/LucaCinquini>
Was going to test the workflow and documentation via chrome. JPL is down. Do you plan to have up today or should I move on to other things?

**Comment by murphysj** [comment]
I was able to go through the workflow. 
Getting set up for globus was confusing a bit on their end. It seemed like it dumped me back to the download before the service was fully set up. It also bounced me between Chrome and FF, probably b/c FF is my default browser but I had to start this in Chrome because of the csrf_token issue.

**Comment by murphysj** [comment]
@LucaCinquini 

I tweaked the template a little because of this experience:

a) to indicate that setup involves and account and an installation
b) got rid of the click "here" constructs. They went out in 1977. 
c) make the registration and such open in a new tab so you don't loose your download

I can not see what this template looks like locally because I don't have globus enabled. Please review to make sure it still looks ok.

**Comment by LucaCinquini** [comment]
Well it’s good you were able to download data, thanks for checking that.
I think you are used to a superior UI, CoG, everything else pales in comparison.
thanks, L

On May 22, 2015, at 1:28 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


I was able to go through the workflow.
Getting set up for globus was confusing a bit on their end. It seemed like it dumped me back to the download before the service was fully set up. It also bounced me between Chrome and FF, probably b/c FF is my default browser but I had to start this in Chrome because of the csrf_token issue.

**Comment by murphysj** [comment]
so true my master

On Fri, May 22, 2015 at 1:31 PM, Luca Cinquini <notifications@github.com>
wrote:

> Well it’s good you were able to download data, thanks for checking that.
> I think you are used to a superior UI, CoG, everything else pales in
> comparison.
> thanks, L
>
> On May 22, 2015, at 1:28 PM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> I was able to go through the workflow.
> Getting set up for globus was confusing a bit on their end. It seemed like
> it dumped me back to the download before the service was fully set up. It
> also bounced me between Chrome and FF, probably b/c FF is my default
> browser but I had to start this in Chrome because of the csrf_token issue.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/691#issuecomment-104748816>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/691#issuecomment-104749244>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753
