### ISSUE TITLE
Table header CSS style only applies to cells at the top of a table

### ISSUE THREAD

**Issue by allynt** [EarthSystemCoG/COG#717]
table header CSS style only applies to cells at the top of a table, even though the table GUI allows you to specify a "header" style in any cell.

**Comment by murphysj** [comment]
I am thinking this is low priority. moving out of 3.0

**Comment by murphysj** [comment]
unable to reproduce this. I created a table and randomly assigned cells to be of type "header" in the cell properties dialog box. The cell did in fact become a header style. 

This may have been happening before we tried to remove the YUI style sheets from effecting everything.
