### ISSUE TITLE
Files not deleted from server when deleted from a project

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#722]
WHO: Joe

It turns out that when someone deletes a document from a project only the POINTER to that document is deleted out of the database. The file itself still remains on the server.

This means that deleted files are showing up in the link browser (powered by the file browser) in the wiki. 

We need to decide whether we want the files deleted.

**Comment by murphysj** [comment]
During the 1/27/15 cog telco it was decided to change the way it works. 

When we delete the file pointer via the interface the file should be deleted from the server.

**Comment by LucaCinquini** [comment]
Done. The document is completely deleted from the file system wether is is uploaded as a standalone document in the project, or attached to a wiki page.

**Comment by murphysj** [comment]
How do I test this since I can't see the files on the server?

**Comment by murphysj** [comment]
any file uploaded i stored under /usr/local/cog/cog_config/site_media/projects/<project>. If you can log onto dev-hydra, you can check that the file is removed from that directory.
           Or you can verify on your local laptop

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
