### ISSUE TITLE
Leave search facet "open" after clicking on "Any"

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#737]
Who: Joe

When using the data search page for NCPP, I constantly run into a
design feature that I think could be improved.  Suppose that I have
chosen a single model from the "Evaluation Data" facet.  When I click
"Any" to reset that facet, the facet closes.  I would prefer it to stay
open as my next action is invariably selecting another model.

**Comment by murphysj** [comment]
at the 3/22/16 call we decided this was no longer applicable.
