### ISSUE TITLE
Use checkboxes for search facet options to allow multiple selection

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#738]
Who: Joe

The other request is that it would be nice to be able to select items
in a facet using check boxes, so that multiple models, or multiple
variables could be selected at once without selecting them all.  An
example from a shopping page,  http://www.zappos.com/mens-sandals~3k 
allows me to choose several brands to include in the results.

**Comment by murphysj** [comment]
This was completed in 2.7
