### ISSUE TITLE
Enhance the search configuration page 

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#768]
WHO: ESGF Review Group

On the Search Configuration Page, project administrators can set search constraints, choose which ESGF node to search, and create search facets. There is no documentation on this page on what is really possible with ESGF-land. At a minimum, we would like to see:

1) Which search URLs are possible. (e.g. pcmdi, badc). Perhaps a pulldown menu? How would this get updated? 
2) What metadata facets are even possible (e.g. see inside the XML file generated by the publishing process). Another pulldown menu? 
3) Others? Examine the config page and see what else might be missing.

**Comment by LucaCinquini** [comment]
For any possible set of search constraints, the available facets can be retrieved from the backend ESGF search service using the query facet=*.
For example:
http://esg-datanode.jpl.nasa.gov/esg-search/search?facets=*&project=obs4MIPs
Note that this query will only return those facets that are configured in the file /esg/config/facet.properties.

**Comment by LucaCinquini** [comment]
The display of available facets based on the list above is done. We need to investigate the possibility of getting rid of the facet.properties file (which must be manually configured by the administrator) and instead enable the Solr "luke" request handler to return  all available facets.

**Comment by murphysj** [comment]
How does a project admin see this list? Do we link to it on some page? Should we?

**Comment by LucaCinquini** [comment]
The list of available facets is shown when the admin clicks on the link "+ Add Facet".

**Comment by LucaCinquini** [comment]
The last piece of the ticket is done too. Changes in the ESGF Search Services have made the facets.properties file obsolete: the list of available facets is retrieved directly from the current local index by means of the "luke" Solr handler deployed on the master Solr on port 8984.

**Comment by murphysj** [comment]
1) Add the following text to the Facet Key help:
Available keys and associated are listed below.

2) Add a period the help text on the label.

3) Change "Available Search Facet Keys, Values" to be 
"Available search facet keys, their associated values and periodicity."

**Comment by LucaCinquini** [comment]
Hi Sylvia,
thanks, but if I may “periodicity” seems to indicate it’s fixed, while in reality that is the number of records that currently have
that value for the facet - subject to change at any time…
thanks, L

On Mar 16, 2015, at 3:27 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


1) Add the following text to the Facet Key help:
Available keys and associated are listed below.

2) Add a period the help text on the label.

3) Change "Available Search Facet Keys, Values" to be
"Available search facet keys, their associated values and periodicity."

**Comment by murphysj** [comment]
Done

**Comment by murphysj** [comment]
What is a better term. I wanted to explain what the numbers mean

**Comment by murphysj** [comment]
just removed periodicity. 

verified on dev-hydra. closing.
