### ISSUE TITLE
Alphabetize data search facets

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#776]
WHO: Sylvia

Currently, the search facets appear in the order they were entered. They should be alphabetized automatically.

**Comment by murphysj** [comment]
Don't know if this should be done along with the other search facet work in 2.11. If not just remove the milestone.

**Comment by LucaCinquini** [comment]
Hi Sylvia,
in general I would avoid assigning anything more to 2.11 - it looks like March is going to be real busy with other projects for me..
thanks, L

On Mar 2, 2015, at 11:44 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't know if this should be done along with the other search facet work in 2.11. If not just remove the milestone.

**Comment by murphysj** [comment]
No problem. Just remove it.

On Mon, Mar 2, 2015 at 11:46 AM, Luca Cinquini <notifications@github.com>
wrote:

> Hi Sylvia,
> in general I would avoid assigning anything more to 2.11 - it looks like
> March is going to be real busy with other projects for me..
> thanks, L
>
> On Mar 2, 2015, at 11:44 AM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> Don't know if this should be done along with the other search facet work
> in 2.11. If not just remove the milestone.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/776#issuecomment-76776417>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/776#issuecomment-76777169>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
In release 3.4, we added the ability to order facets as we please #635 . That eliminates the need for automatic alphabetization.
