### ISSUE TITLE
Delete groups on project deletion

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#788]
WHO: Sylvia

When a project is deleted the user and admin groups are not. We had a bunch to clean out. 

These should be deleted along with the project.

**Comment by LucaCinquini** [comment]
This is now done - note that the project MUST be deleted through the CoG interface to trigger the deletion of associated objects, not the django admin interface.
Additionally, this works also for remote projects: if a project belongs to a remote site and is deleted there, the next time the sites are synchronized, the local stub for the remote project (and the corresponding groups) will be deleted.

**Comment by murphysj** [comment]
What do you mean by remote sites? Does the CoG Admin interface show
projects from federated nodes? Would a site admin on one node be able to
delete a project on another node?

On Wed, Sep 2, 2015 at 6:56 AM, Luca Cinquini <notifications@github.com>
wrote:

> Assigned #788 <https://github.com/EarthSystemCoG/COG/issues/788> to
> @murphysj <https://github.com/murphysj>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/788#event-398893832>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
verified on cu dev
