### ISSUE TITLE
Make it easier for admins to change a user's password

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#857]
WHO: Luca

Currently, it is a multi-step process to change a user's password, which involves changing the password in the Django interface, then logging in as that user and changing the password again (so that it propagates to ESGF), on the user's "my profile".

**Comment by LucaCinquini** [comment]
I modified the 'password_update' template and view to support a double functionality: it can now be used by the user to change their password, or by an administrator to do the same thing.

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
