### ISSUE TITLE
Create new "Peer Node" widget

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#862]
WHO: Sylvia

This will replace the listing of peer nodes on the current ESGF WebFE. 

It will need to be automatically populated by a configuration script, and appear on the right below the data widget

**Comment by LucaCinquini** [comment]
This is now done, the widget shows the listing (ordered alphabetically) of all federated and enabled peer sites.
If the list becomes very long, we may want to limit the vertical size of the widget and insert a scrollbar. Sylvia could you work on that, and possibly any additional styling ?

**Comment by LucaCinquini** [comment]
Another question is wether we want to enable a project-level flag to control wether or not this widget gets included. Right now, the "Data Search" widget has such a flag, but the "News" and "Project Browser" widgets do not - they are always included if the right column is enabled.

**Comment by murphysj** [comment]
checked this out at JPL. Several comments:

a) We only want this enabled for the project home page. Not sure it should
be an option for others
b) We need to decide whether we are Nodes or Sites and stick with it
c) It should be ESGF-CoG not ESGF/CoG, we decided on that one a while back
d) Is "peer" the right word? Do users know what that means? Should it be
"federated" ?

On Mon, Aug 17, 2015 at 6:39 AM, Luca Cinquini <notifications@github.com>
wrote:

> Another question is wether we want to enable a project-level flag to
> control wether or not this widget gets included. Right now, the "Data
> Search" widget has such a flag, but the "News" and "Project Browser"
> widgets do not - they are always included if the right column is enabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/862#issuecomment-131801069>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
We have deployed this on hydra for NOAA with hardwired links since federation is currently turned off.
