### ISSUE TITLE
Integrate CoG with ESGF Apache httpd

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#890]
Who: Luca

Once the ESGF software stack includes an Apache httpd server, we need to configure the CoG installation to run with mod_wsgi from behind that server

**Comment by LucaCinquini** [comment]
CoG can now be run behind the ESGF-configured Apache httpd server. For the ESGF 1.9 release, CoG will still run on a separate port 8000, and will not be the default ESGF user interface. Later we can either a) redirect all requests to hostname:80/443 that are not solr/, threads/., etc to https://hostname:8000
or b) use a separate domain name for CoG such as "cog-esgf.esrl.noaa.gov"

Note also that the installation script has been modified so that $COG_CONFIG_DIR is owned by apache:apache.

**Comment by LucaCinquini** [comment]
Additionally, we will configure Apache to use WSGIPythonHome pointing to the CoG virtual environment, so that all instances use exactly the same packages. The CoG venv will be built from a standard, bare-bone ESGF Python installation that is version 2.7.9 and contains only setup_tools, pip and virtualenv.

**Comment by LucaCinquini** [comment]
Note that of the two options above, a) is probably the easiest, and will work just fine.
Additionally, it is recommended to run port 8000 under SSL so that:
o) passwords will not be sent in the clear when users register or change their password
o) Globus Online integration requires that the site URLs are HTTPS

**Comment by LucaCinquini** [comment]
The only remaining issue is that when CoG is run using the ESGF-configured Apache, Safari will stop working because of the size of the bundle that contains all the ESGF certificates. We will need top ask Prashanth to make the bundle smaller.

**Comment by murphysj** [comment]
@LucaCinquini 
Can this be closed?

**Comment by LucaCinquini** [comment]
No that one last issue remains. I think we should move this ticket to the next release perhaps ?

**Comment by murphysj** [comment]
@LucaCinquini 
I assume this has been postponed until further notice and should be removed from 2.13?

**Comment by murphysj** [comment]
@LucaCinquini
Can this be closed as part of 2.14, or was the integration you did with the other nodes something else?

**Comment by LucaCinquini** [comment]
I think it will be completed as part of 2.15
L

On Aug 31, 2015, at 12:43 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucaCinquini<https://github.com/LucaCinquini>
Can this be closed as part of 2.14, or was the integration you did with the other nodes something else?

**Comment by LucaCinquini** [comment]
Done, CoG now runs behind the Apache httpd server as part of the ESGF software stack.
