### ISSUE TITLE
Integrate ESGF's OpenID via pulldown solution

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#892]
WHO: Cecelia

ESGF is going to change how OpenID works. Users will be able to use a pulldown menu to select their node. We could then use this to automatically generate  users OpenID.

This is dependent upon ESGF developing

**Comment by murphysj** [comment]
Luca indicates this is not working well and has issues at various nodes.

**Comment by LucaCinquini** [comment]
Indeed - moving to next release. It needs to be fixed by BADC on the server side.

**Comment by murphysj** [comment]
Hi Luca,

Then you need to comment it out in RC 2.13. The pull down for each of the
ESGF nodes in there on the login page.

S

On Fri, Jun 26, 2015 at 4:58 PM, Luca Cinquini <notifications@github.com>
wrote:

> Indeed - moving to next release. It needs to be fixed by BADC on the
> server side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/892#issuecomment-115912232>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
duplicate of #1168. Adding to milestone and closing.
