### ISSUE TITLE
Expose number of projects and users at each node for metric collection

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#906]
WHO: Sylvia

We need to get number of projects and number of people per site.

**Comment by murphysj** [comment]
@LucaCinquini 
What is the URL to do this for projects? 

Do we need a template so Cecelia can do it? Seems like it would have to be accessible to every Site Admin out there then. Would we want that?

**Comment by LucaCinquini** [comment]
I have implemented this as part of the CoG site synchronization page. Now, as a result of synchronizing with all the federated CoGs, each site will report the total number of projects and the total number of users. Will demo at conference call today.

**Comment by murphysj** [comment]
verified on cu-dev. closing.
