### ISSUE TITLE
Document CoG Administration on the CoG site

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#911]
WHO: Sylvia

We decided to break out installation from routine administration, so I am creating a separate ticket for that.

**Comment by LucaCinquini** [comment]
I updated the installation guide with the new rules for the super-user username and password,

**Comment by murphysj** [comment]
If you are happy with it, go ahead and close the ticket.

On Fri, Jan 30, 2015 at 6:34 AM, Luca Cinquini <notifications@github.com>
wrote:

> I updated the installation guide with the new rules for the super-user
> username and password,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/911#issuecomment-72200983>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753
