### ISSUE TITLE
Enable insertion of URL that carry the user openid as extra parameter

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#933]
Who: Jebb Stewart

Do you store the Openid user name in any environment variable we could pass along when a user clicks a link?  We don't need it soon, but future releases it might be helpful to have the capability construct a link with a hidden parameter that includes a user's openid login.

**Comment by murphysj** [comment]
During 2016 prioritization, it was decided to close this as no longer applicable. We are not really supporting those guys anymore.
