### ISSUE TITLE
Create separate "all users" page

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#944]
WHO: Sylvia

The "all users" page uses the same view as the "current users" and "pending users". It should not because they are different.

the "all users" page needs to include the number of projects and last login. It needs to exclude the membership info, since it is outside of the project. The cancel and submit buttons don't make sense because we are not submitting anything. Finally, the header lists the project where the link was clicked which means nothing.

**Comment by LucaCinquini** [comment]
Done. The general URL to view all system users, including number of projects and last login, is:

http://hostname:port/cogadmin/users/

and is reserved to CoG administrators. It shows up as "List System Users" item in left menu.

The previous functionality is still available in the project administrator panel as link "List all Site Users", which invokes a URL of the form: http://hostname:port/membership/list/all/cog/

**Comment by murphysj** [comment]
Page verified. Link works. URL is correct. Issue with one of the metrics. That is covered under ticket:

**Comment by murphysj** [comment]
closing.
