### ISSUE TITLE
Upgrade the deprecated package django.contrib.comments with the standalone package django_comments

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#959]
Who: Luca

django.contrib.comments has been deprecated and will be discontinued in django 1.8

**Comment by LucaCinquini** [comment]
Done. All current comments functionality seems to still work.

**Comment by murphysj** [comment]
FYI, current comments on dev-hydra do not work. They map be the deprecation having taken hold.

**Comment by LucaCinquini** [comment]
Uhm, I have not upgraded the installation on dev-hydra at all… Hopefully the will start working again once I redeploy with the new django comments package.
L

On Jan 8, 2015, at 11:39 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


FYI, current comments on dev-hydra do not work. They map be the deprecation having taken hold.

**Comment by murphysj** [comment]
FYI. I can't tell if what I see is a new package or not, so Luca will have to close this. They are working at the moment. Full testing may reveal more.
