### ISSUE TITLE
Change default CoG administrator username to "rootAdmin"

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#960]
Who: Nicolas Carenton

Nicolas is testing installation of CoG within ESGF environment, and got confused between the newly created CoG "admin" user, and the traditional ESGF node administrator "rootAdmin". It would be less confusing to use the username "rootAdmin" as the default CoG administrator.

**Comment by LucaCinquini** [comment]
Hi Sylvia, I haven't worked on this yet...

**Comment by murphysj** [comment]
Then move it to 2.10. It was still in 2.9.

On Tue, Jan 20, 2015 at 9:18 AM, Luca Cinquini <notifications@github.com>
wrote:

> Hi Sylvia, I haven't worked on this yet...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/960#issuecomment-70681405>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
This has been implemented. Now, the very first time CoG is installed:

o A new user "rootAdmin" will be created with site administrator privileges. 

o In addition, when performing an ESGF installation:
    - the rootAdmin password is read from the standard ESGF file /esg/config/.esgf_pass.
    - The "rootAdmin" user is assigned the standard ESGF openid "https://hostname/esgf-idp/openid/rootAdmin" which should already exist in the ESGF database

o Otherwise, when performing an installation with esgf=false, the rootAdmin user is assigned a default password, which should immediately be changed.

Note that the above happens ONLY when the database is first populated, not any time after.

**Comment by murphysj** [comment]
verified on dev-hydra. saw change in django admin interface and logged in using that new name.
