### ISSUE TITLE
Private projects showing up in "My Profile"

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#964]
WHO: Sylvia
found in 2.9 testing. very rapid. need to verify.

**Comment by LucaCinquini** [comment]
It used to be that a project showed up in the user profile under either of these conditions:
a) The project is public
b) The logged in user is the user himself

I now added the following two conditions:
c) The logged in user is a site administrator
d) The logged in user is a project administrator

So private projects will not show up in the project listings unless one of the conditions b), c) or d) is satisfied,

**Comment by murphysj** [comment]
To test this I created a fake users and subscribed them to two projects one private and one public. When logged in as admin I can see both listed in the project affiliations. While logged out and viewing and Joe Public, I see only the public one. Closing.
