### ISSUE TITLE
Figure out better way to deal with federated password updates

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#967]
WHO: Sylvia

Found in 2.9 testing.

a) Have a call to explain the issue and brainstorm.

**Comment by LucaCinquini** [comment]
Maybe we should detect wether a user has logged in with an external openid (for example from DKRZ) and redirect to the ESGF IdP at that node.

**Comment by LucaCinquini** [comment]
This has been done.

The 'My Profile' link will always redirect the CoG user to their home site - i.e. the CoG site where the user first created (and maintains) an account. On that page:

o If the user openid is issued by the same site, the 'Change my password' link will redirect to the CoG page for changing password. This page will change the password in the CoG database and propagate the change to the associate ESGF node.

o If the her openid is issued by another site, the 'Change my password' link will redirect the user to the legacy ESGF UI for changing the password (i.e. the old web front end login page with link for changing the password).

**Comment by murphysj** [comment]
test: go to jpl, get jpl openid, login to cog. this will create a new account. then go to my profile, the link to to change password should redirect back to jp.

**Comment by murphysj** [comment]
In my sandbox, I created several accounts. None have an associated openID, including admin. This means the profile page no longer works.

**Comment by murphysj** [comment]
It's because you don't have an ESGF node installed, so no openid... Maybe  there's a way to make the profile page work no matter what...

**Comment by murphysj** [comment]
Hi Sylvia,
I think I fixed this problem, it was simply related to the fact that the template for the user profile was trying to access the user openid to show the “change password” link.
Now I made it such that if the user has no openid, he/she cannot change the password - in this case, we’ll change the password through the django admin interface (since ALL real user must now have an openid to login).
Please let me know if this solved your problem.

thanks, Luca

**Comment by murphysj** [comment]
It is working now.

**Comment by murphysj** [comment]
verified on dev-hydra. closing.
