### ISSUE TITLE
Make entire forum breadcrumb trail have links

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#972]
WHO: Sylvia
Found in 2.9 testing.

Currently only the topic is linked. The thread should also be linked.

**Comment by LucaCinquini** [comment]
You mean only the Forum is linked ?
The thread should not be linked because it's the very same page.

**Comment by murphysj** [comment]
I see all the topics are on the same page.

I just looked at pybbm. On their main page, they only list the topics, with a list of the number of threads under each. You click on the topic and go to that topic's page. Then  all the threads are listed there. 

We are putting everything on one page and linking just to individual threads. 

Not sure our current design is scalable. How difficult would it be to break this up at some future date, or is this something we need to discuss now?

**Comment by murphysj** [comment]
Luca removed the intermediary pages that have threads on their own page. Right now everything is consolidated. If we every reinstate that page, the breadcrumb trail will get modified when that work is done. 

not applicable.
