### ISSUE TITLE
YSD when clicking "Remove all displayed results from Data Cart" for Admin account only

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#973]
WHO: Sylvia
Found in 2.9 testing

This effects the admin account only. 

To reproduce. 

a) Login as admin
b) Do a data search
c) Add a few items to the datacart
d) click on Remove all displayed results from the Data Cart

**Comment by LucaCinquini** [comment]
Was not able to reproduce this... Maybe you can show me on Skype ?

**Comment by murphysj** [comment]
Lets test tomorrow. I can't login as the new rootAdmin at all now on
dev-hydra using login2 to even verify.

On Wed, Jan 28, 2015 at 3:03 PM, Luca Cinquini <notifications@github.com>
wrote:

> Was not able to reproduce this... Maybe you can show me on Skype ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/973#issuecomment-71926104>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
Tried again after 2.9.1 installed on dev-hydra. Can't reproduce at this point. 
Will close for now. If we see it again, we will reopen.
