### ISSUE TITLE
Number of projects returned inconsistently

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#976]
WHO: Sylvia

I am trying to debug an inconsistency in the listing of the number of projects reported for users.

Attached are two images. The first shows the page that we see when we click on a user from any of our user listings. Note the number of projects is 1, which is not correct.

If you were to click on the link that says "View User Profile at NOAA ESRL ESGF-CoG", you get the second image. The number of projects is listed as 0, which is correct.

What concerns me more is that the number is different depending upon which machine is serving up the info.

Initial page
![seo_1](https://cloud.githubusercontent.com/assets/1512704/5877859/df9e57f8-a2df-11e4-90d3-857d487d58af.png)

Following page
![seo_2](https://cloud.githubusercontent.com/assets/1512704/5877860/dfa0cf7e-a2df-11e4-9adb-0d354f1b75d8.png)

**Comment by murphysj** [comment]
I found another strange case. We have several duplicate accounts. When  a user has two accounts, same email address, different user name, it seemed liked the number of projects list for both was the CUMULATIVE of all their accounts. 

Not sure how that could be happening, but something else to investigate.

**Comment by LucaCinquini** [comment]
Ok I have investigated the issue and there are two reasons for the discrepancy:

o First of all, private projects are NOT shared across sites

o But even more importantly, the number of projects a user belongs to is only updated when the user logs onto a CoG site. So if, for example, a user always logs onto CoG-CU but never into CoG-NOAA, the number of projects shown on CoG-CU will be greater than 0, while the number of projects shown at CoG-NOAA will be 0.

The reason for only updating at user login is to avoid running massive jobs that loop over all the users and all the sites. The question is wether we care about showing the number of projects - maybe we should just forget about that piece of information.

**Comment by murphysj** [comment]
actually, it is very important. It identifies users who have account but
never joined a project. This can identify bogus accounts.

I think we should keep it, but just interpret the data correctly.



On Wed, Jan 28, 2015 at 2:44 PM, Luca Cinquini <notifications@github.com>
wrote:

> Ok I have investigated the issue and there are two reasons for the
> discrepancy:
>
> o First of all, private projects are NOT shared across sites
>
> o But even more importantly, the number of projects a user belongs to is
> only updated when the user logs onto a CoG site. So if, for example, a user
> always logs onto CoG-CU but never into CoG-NOAA, the number of projects
> shown on CoG-CU will be greater than 0, while the number of projects shown
> at CoG-NOAA will be 0.
>
> The reason for only updating at user login is to avoid running massive
> jobs that loop over all the users and all the sites. The question is wether
> we care about showing the number of projects - maybe we should just forget
> about that piece of information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/976#issuecomment-71922790>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
Talking with Luca we agreed to remove the number of projects because it is not possible to track this across nodes. the information is not shared.

**Comment by LucaCinquini** [comment]
Upon further discussion and work, this is now much improved. Every time a user profile paged is displayed, CoG queries the federation for updated information about that user, and displays it - without saving it to the local database, though.
At the same time, when the user session is too old, the same machinery is invoked and the federated information IS saved into the database, so that the user can access projects through the "My Projects" tab.

**Comment by LucaCinquini** [comment]
Things to consider:

o The "My Projects" tab still does not include private projects at other sites, because private projects are NOT shared among sites. I think we should remove this restriction and share ALL active projects, including private, because private projects will not be accessible anyhow unless the user has the appropriate privileges

o Should we display the user roles (admin, user) in the user profile page ?

**Comment by murphysj** [comment]
Hmmm,

I would be inclined to list private projects on both the user profile page
AND the My Projects tab of the Project Browser. Cecelia may think
differently. Lets discuss on the 2/3/15 cog telco.

WRT Role: I think it would be useful for site admins to see who project
admins are and potentially for other users to see who their project admins
are, so yes I think displaying role would be useful. We could expand the
table of projects to list the project and the role.



On Sat, Jan 31, 2015 at 4:43 AM, Luca Cinquini <notifications@github.com>
wrote:

> Things to consider:
>
> o The "My Projects" tab still does not include private projects at other
> sites, because private projects are NOT shared among sites. I think we
> should remove this restriction and share ALL active projects, including
> private, because private projects will not be accessible anyhow unless the
> user has the appropriate privileges
>
> o Should we display the user roles (admin, user) in the user profile page ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/976#issuecomment-72314629>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
We agreed on the 2/10/14 CoG Tech telco that we are going to federate private projects. That is now ticket #997. 

This issue is closed.
