### ISSUE TITLE
Upgrade ESGF/CoG Installation Script

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#980]
Who: Luca

We need to modify the ESGF installation script to conform to the new requirements from Zed - answer "new version", "old version", "install path"

**Comment by murphysj** [comment]
Luca reported that initial work was done on this but that ESGF still needs to decide how they want this to look. Until finalized, we will keep moving it along from release to release.

**Comment by LucaCinquini** [comment]
ESGF administrators have reported that they are able to install and start CoG on port 8000. Closing.
