### ISSUE TITLE
Enable admin searches on user profiles

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#982]
Who: Luca

It would be convenient to enable searching on the django admin interface for UserProfile objects.

**Comment by LucaCinquini** [comment]
Done - very easy to enable with a few lines of code like this, in case it needs to be done for other objects:

class UserProfileAdmin(admin.ModelAdmin):
    search_fields = ['user__username', 'user__first_name', 'user__last_name', 'user__email']
admin.site.register(UserProfile, UserProfileAdmin)

**Comment by murphysj** [comment]
verified on dev-hydra. Closing.
