### ISSUE TITLE
Enforce 508 compliance at JPL

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#983]
Who: JPL administrators

JPL administrators scan the CoG node at esg-datanode.jpl.nasa.gov:8000 and found a list of 508-non-compliant pages. All issues need to be solved before JPL can authorize a PAR on this application,

**Comment by LucaCinquini** [comment]
After a few iterations, JPL has approved the site for 508 compliance. The last step is to add Google Analytics.

**Comment by murphysj** [comment]
what did you have to do besides the logo?

On Fri, Jan 30, 2015 at 3:28 PM, Luca Cinquini <notifications@github.com>
wrote:

> After a few iterations, JPL has approved the site for 508 compliance. The
> last step is to add Google Analytics.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/983#issuecomment-72281449>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
There were a few pages that needed "alt" tags for images or "label" elements for input fields - for example, the registration page, or the forgot password page.

I am moving the Google Analytics requirements to a different ticket, this should be considered completed.

**Comment by murphysj** [comment]
I went through the code base for 2.9 and added all of the label-for
elements. Did you upgrade before rescanning? I hope we did not conflict
there.

On Mon, Feb 2, 2015 at 3:44 AM, Luca Cinquini <notifications@github.com>
wrote:

> There were a few pages that needed "alt" tags for images or "label"
> elements for input fields - for example, the registration page, or the
> forgot password page.
>
> I am moving the Google Analytics requirements to a different ticket, this
> should be considered completed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/983#issuecomment-72437096>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
I pulled the latest version of the code, I think you simply missed some elements - no problem. Or perhaps the JPL scan is more intrusive
than the one you were working with.
thanks, L

On Feb 2, 2015, at 8:59 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:

I went through the code base for 2.9 and added all of the label-for
elements. Did you upgrade before rescanning? I hope we did not conflict
there.

On Mon, Feb 2, 2015 at 3:44 AM, Luca Cinquini <notifications@github.com<mailto:notifications@github.com>>
wrote:

> There were a few pages that needed "alt" tags for images or "label"
> elements for input fields - for example, the registration page, or the
> forgot password page.
>
> I am moving the Google Analytics requirements to a different ticket, this
> should be considered completed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/983#issuecomment-72437096>.
>



--
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
Phone: 303-497-7753

**Comment by murphysj** [comment]
Did you fix those elements just at JPL or in the code base? I used selenium
to find instances. Probably easy to miss something.

On Mon, Feb 2, 2015 at 9:04 AM, Luca Cinquini <notifications@github.com>
wrote:

> I pulled the latest version of the code, I think you simply missed some
> elements - no problem. Or perhaps the JPL scan is more intrusive
> than the one you were working with.
> thanks, L
>
> On Feb 2, 2015, at 8:59 AM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
> I went through the code base for 2.9 and added all of the label-for
> elements. Did you upgrade before rescanning? I hope we did not conflict
> there.
>
> On Mon, Feb 2, 2015 at 3:44 AM, Luca Cinquini <notifications@github.com
> <mailto:notifications@github.com>>
> wrote:
>
> > There were a few pages that needed "alt" tags for images or "label"
> > elements for input fields - for example, the registration page, or the
> > forgot password page.
> >
> > I am moving the Google Analytics requirements to a different ticket,
> this
> > should be considered completed.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/EarthSystemCoG/COG/issues/983#issuecomment-72437096>.
>
> >
>
>
>
> --
> ******************************************
> Sylvia Murphy
> NESII/CIRES/NOAA Earth System Research Laboratory
> 325 Broadway, Boulder CO 80305
> Time Zone: U.S. Mountain
> Web: http://www.esrl.noaa.gov/nesii/
> Email: sylvia.murphy@noaa.gov<mailto:sylvia.murphy@noaa.gov>
> Phone: 303-497-7753
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/983#issuecomment-72481516>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/983#issuecomment-72482436>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
JPL says we are good to go. Closing.
