### ISSUE TITLE
YSD when uploading none image files to the wiki

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#984]
WHO: Sylvia

You see this in the image dialog box when you try to upload a non-image file via the image browser in the wiki. 

a) Open the wiki and the image browser
b) Select a text file
c) Click send it to the server

note that for 2.10 I have increased the size of the dialog box so you can actually see the error. 

We need a more graceful error, like "you can not upload non-image files via this interface" or some such.

**Comment by LucaCinquini** [comment]
I don’t think it’s possible because we don’t control that interface - we could try to hack it but it might not be a good idea in case we need to upgrade it to a new version.
L

On Jan 30, 2015, at 1:15 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


WHO: Sylvia

You see this in the image dialog box when you try to upload a non-image file via the image browser in the wiki.

a) Open the wiki and the image browser
b) Select a text file
c) Click send it to the server

note that for 2.10 I have increased the size of the dialog box so you can actually see the error.

We need a more graceful error, like "you can not upload non-image files via this interface" or some such.

**Comment by murphysj** [comment]
This is not the interface ticket. This is a ticket indicating that the
error produced when uploading non-images is a YSD. It just happens to land
in the image browsers.

Are you saying that it is the browser itself that causes the YSD?

On Fri, Jan 30, 2015 at 3:29 PM, Luca Cinquini <notifications@github.com>
wrote:

> I don’t think it’s possible because we don’t control that interface - we
> could try to hack it but it might not be a good idea in case we need to
> upgrade it to a new version.
> L
>
> On Jan 30, 2015, at 1:15 PM, Sylvia Murphy <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> WHO: Sylvia
>
> You see this in the image dialog box when you try to upload a non-image
> file via the image browser in the wiki.
>
> a) Open the wiki and the image browser
> b) Select a text file
> c) Click send it to the server
>
> note that for 2.10 I have increased the size of the dialog box so you can
> actually see the error.
>
> We need a more graceful error, like "you can not upload non-image files
> via this interface" or some such.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/EarthSystemCoG/COG/issues/984>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/984#issuecomment-72281624>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by LucaCinquini** [comment]
I think I improved the error handling much, although it is difficult to interact with the file browser widget and CKeditor. There is no more YSD. If a user uploads a non-valid image, an alert pops up, and a standard error image is displayed instead. You are welcome to find a better error image if you wish, and replace the current one.

**Comment by murphysj** [comment]
That works for me. I did change the error message slightly to indicate what are valid formats. 
Once this gets deployed on dev-hydra I will confirm and close.

**Comment by murphysj** [comment]
verified new error message on dev-hydra. closing.
