### ISSUE TITLE
Redirect to proper site when canceling a project membership

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#985]
Who: Luca

I realized that the current user profile page, where a user can decide to cancel their membership, always targets the current site, and not the site where the project is hosted. This is incorrect.

**Comment by LucaCinquini** [comment]
Fixed - now the view will redirect to the proper site where the project is hosted.

**Comment by murphysj** [comment]
How should I test this? All the projects on dev-hydra are hosted there, so cancelling out of one of those projects who take me to another node?

**Comment by LucaCinquini** [comment]
You can try to use the dev-hydra admin interface to federate with CoG/ESRL, then get a membership in HIWPP and try to cancel it - it should redirect you back to CoG/ESRL.
thanks, L

On Feb 6, 2015, at 3:21 PM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


How should I test this? All the projects on dev-hydra are hosted there, so cancelling out of one of those projects who take me to another node?

**Comment by murphysj** [comment]
I wonder if this is the correct behavior. Someone is in their profile, they hit cancel membership. They do so, they should be redirected back to their profile, not to the project they just cancelled. Is that what currently happens?

**Comment by LucaCinquini** [comment]
The membership MUST be canceled on the site where the group is managed. After that is done, we could redirect the user to their profile, wherever that is. Right now, they are simply shown a "Membership Cancelled" confirmation page (on that site where the group is managed).

**Comment by murphysj** [comment]
I think redirecting back to the profile is the way to go.

**Comment by murphysj** [comment]
I tried testing this. 

In order to be part of a dev-hydra fake projects (e.g. cog) and a non dev-hydra real project (e.g. hiwpp), the user accounts have to sync. 

I created a fake account on hydra and joined the hiwpp project, but I can not see that user from dev-hydra in order to join the fake projects. 

Am I missing something here?

**Comment by LucaCinquini** [comment]
I changed the view to redirect to the user own profile after the membership is cancelled.
We can deal with the testing issue during our call today.

**Comment by murphysj** [comment]
Luca and I determined we can not test this out of production because we don't have two test nodes. Will reopen if it is an issue.
