### ISSUE TITLE
Unfriendly message when bad openid is used on CoG/CU site

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#986]
Who: Sylvia

I tried putting a bogus openid into the login box at CU (on purpose), but got a non-graceful error.

**Comment by LucaCinquini** [comment]
This test uncovered an important issue: if the site is NOT configured with a back-end ESGF node and corresponding IdP whitelist, then an error on openid authentication results in a non-friendly error message. Additionally, IdP whitelisting is not enforced.

Note that the same action on the CoG/NOAA site cause a friendly error message to be displayed on the login page, because that site is backed-up by an ESGF node.

**Comment by LucaCinquini** [comment]
To solve this issue, I moved the IDP_WHITELIST setting outside of the [ESGF] section of cog_settings.cfg into the [DEFAULT] section. As a consequence, all sites will try to use an IdP whitelist, wether they have an ESGF node or not. The default location of the whitelist is /esg/config/esgf_idp_static.xml, but off course the site administrator can manually edit the cog_settings.cfg file to point to any location.

Sylvia, if you want to install a whitelist file on your laptop, simply copy the file from hydra or dev-hydra or from CU at $COG_CONFIG_DIR/esgf_idp_static.xml

**Comment by murphysj** [comment]
One question for clarification here. In a comment above you state:
"Note that the same action on the CoG/NOAA site cause a friendly error message to be displayed on the login page, because that site is backed-up by an ESGF node."

This issue was an UNFRIENDLY message at CU. Is the above note a typo?

**Comment by LucaCinquini** [comment]
No, I was simply testing wether the problem was intrinsic to the software, or specific to a site configuration. It turns out it was the latter.
thanks, L

On Feb 2, 2015, at 10:38 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


One question for clarification here. In a comment above you state:
"Note that the same action on the CoG/NOAA site cause a friendly error message to be displayed on the login page, because that site is backed-up by an ESGF node."

This issue was an UNFRIENDLY message at CU. Is the above note a typo?

**Comment by murphysj** [comment]
Not sure I tested this correctly or not, but on dev-hydra, I entered a bad openID and got a user-friendly error message. After the release we will have to check this at CU. Closing.
