### ISSUE TITLE
Allow Google Analytics code to be site-specific

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#987]
Who: Luca

Currently, all CoG instances load Google Analytics code that contains NOAA-specific parameters (agency=NOAA, sub-agency=ESRL). We should make this code site-specific.

**Comment by LucaCinquini** [comment]
This is now done using the same template-loading strategy as the custom header and footer. By default, the CoG instance will load a file cog/common/google_analytics.html that is empty. Sites that want to insert google analytics must place a customized version of that file into the location $COG_CONFIG_DIR/mytemplates/cog/common/google_analytics.html.

This solution has already been deployed for the prototype JPL site and will have to be implemented for NOAA, CU when this release is deployed.

Sylvia, could you please document this procedure on the CoG admin guide ?

**Comment by LucaCinquini** [comment]
As part of this ticket, we may want to review which parameters to feed to the GA script.

a) Currently, for JPL: agency=NASA and sub-agency=JPL-CoG (mandated)

b) Currently for NOAA: agency=NOAA and sub-agency=ESRL
Do we want to change this to sub-agency=ESRL-CoG ?

c) What to do for CU ? Right now I have a template with: agency=CU and sub-agency=CoG

**Comment by murphysj** [comment]
CU should not have the google analytics installed. The current google
implementation is a federal reporting code.

On Mon, Feb 2, 2015 at 3:51 AM, Luca Cinquini <notifications@github.com>
wrote:

> As part of this ticket, we may want to review which parameters to feed to
> the GA script.
>
> a) Currently, for JPL: agency=NASA and sub-agency=JPL-CoG (mandated)
>
> b) Currently for NOAA: agency=NOAA and sub-agency=ESRL
> Do we want to change this to sub-agency=ESRL-CoG ?
>
> c) What to do for CU ? Right now I have a template with: agency=CU and
> sub-agency=CoG
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/987#issuecomment-72438026>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
I would leave the NOAA sub-agency to be ESRL. That is what they requested when we set it up.

**Comment by murphysj** [comment]
I am writing the documentation for this. Google Analytics is a paragraph of code with various parameters etc. 

I would suggest just passing the entire paragraph since what is required in terms of parameters will vary from agency to agency.

**Comment by murphysj** [comment]
For dev-hydra, I have NOT installed any site specific google analytics into $COG_CONFIG_DIR/mytemplates/cog/common. So if you look at the source for any page, you should see nothing… Then maybe you can check again after release that the NOAA instance has NOAA-specific google analytics.

        thanks, Luca

**Comment by murphysj** [comment]
I did do a source on dev-hydra and saw no google analytics. closing.
