### ISSUE TITLE
Change where Metrics is located in the Upper Navigation bar

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#991]
WHO: Cecelia

C does not like this under Governance. Where to put it is the issue. There is really not space in the upper nav bar.

**Comment by murphysj** [comment]
This will move from being a sub-nav item under Governance, to being in the upper navigation bar proper. 

Location is after Roadmaps

**Comment by LucaCinquini** [comment]
Done.

**Comment by murphysj** [comment]
You have this is the wrong spot. It is showing up before Governance in the upper nav bar.

**Comment by LucaCinquini** [comment]
Well the ticket above says "after Roadmaps", not "after Governance"...

**Comment by murphysj** [comment]
That is correct, the link should show up after Roadmaps. It is currently
showing up after developers.

On Tue, Mar 10, 2015 at 10:56 AM, Luca Cinquini <notifications@github.com>
wrote:

> Well the ticket above says "after Roadmaps", not "after Governance"...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EarthSystemCoG/COG/issues/991#issuecomment-78097605>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by murphysj** [comment]
I see the issue, I did not have Roadmaps turned on in my test.

Cecelia wanted it to look like ESMF, but cog has a different order. 

Lets see what she says.

**Comment by murphysj** [comment]
Cecelia agreed on 3/10/15 demo.
