### ISSUE TITLE
Unsubscribe emails being sent w/o prior subscription

### ISSUE THREAD

**Issue by murphysj** [EarthSystemCoG/COG#992]
WHO: Sylvia

I am getting these emails:

User: sylvia murphy has requested to leave the email list: cog_info@list.woc.noaa.gov
User profile: https://dev-hydra-httpd.esrl.svc/user/detail/575/

Even when a user has never requested to be on the cog_info list. 

The way the code reads is that these emails should only be sent IF a user changes their status from subscribe to unsubscribe. 

Now I am seeing them when they first register but don't opt into cog_info.

**Comment by murphysj** [comment]
I had been seeing these emails lately but could not PROVE that I was getting them wlo prior subscription until I created a JPL OpenID to test the new federated password change mechanism. 

When I created my profile on cog, I did not select the mailing list option but got the above email, so I know it was true.

**Comment by LucaCinquini** [comment]
I verified this. I now changed the code to send un-subscription emails only for existing users, not when an account is first created.

**Comment by murphysj** [comment]
tested on dev-hydra. Created a new account but opted OUT of the mailing list. I did NOT get an email requesting to unsubscribe. Closing.
