### ISSUE TITLE
Federate project tags

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#993]
Who: Cecelia

I noticed that the tag search only seems to work on the local node.
Is this something that you anticipate changing? It would be nice
if it could look across all the projects in the browser.

**Comment by LucaCinquini** [comment]
Hi Cecelia,
I believe this works already - tags are exported by each site as part of their projects metadata.
For example, I started from the CU site and used tag="Earthcube", which returns the project CoupledNEMS at NOAA (and two projects at CU). Vice versa, I started at NOAA and used tag="Model coupling", which returns 2 projects at CU (you must be in the All tab to see them).
Please let me know if this is not the case for your.

**Comment by murphysj** [comment]
I just tested this and saw the same thing that Cecelia did. Tags are not federated. 

a) I went to COG NOAA and created a new tag...NOAA and assigned it to Coupled NEMS.
b) I went to COG CU and the NESII project and tried to tag it. NOAA was not available in the list of possible tags.
c) So then I duplicated the the NOAA tag and tagged NESII with it. 
d) On CU when I put NOAA into the project browser, only NESII showed up. 
e) Similiarly, I went back to COG NOAA and did a tag search on NOAA and only Coupled NEMS showed up. 

Tags are not federated.

**Comment by LucaCinquini** [comment]
Can you try with an existing tag, like I explained in the ticket ? Federation is not instantaneous, projects are synchronized every few hours, I believe.
L

On Feb 11, 2015, at 10:44 AM, Sylvia Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


I just tested this and saw the same thing that Cecelia did. Tags are not federated.

a) I went to COG NOAA and created a new tag...NOAA and assigned it to Coupled NEMS.
b) I went to COG CU and the NESII project and tried to tag it. NOAA was not available in the list of possible tags.
c) So then I duplicated the the NOAA tag and tagged NESII with it.
d) On CU when I put NOAA into the project browser, only NESII showed up.
e) Similiarly, I went back to COG NOAA and did a tag search on NOAA and only Coupled NEMS showed up.

Tags are not federated.

**Comment by murphysj** [comment]
I wanted to do an independent test. I don't either Cecelia nor I knew that federation was not instantaneous. She was probably seeing the lag too.

I waited and went back to my test and see the federation of tags. 

Closing.
